' ' > TableLoad_Main.sql
type _Tables.sql >> TableLoad_Main.sql
type .\TableLoad_01_Keywords.sql >> TableLoad_Main.sql
type .\TableLoad_10_Raiders.sql >> TableLoad_Main.sql
type .\TableLoad_20_Lawbots.sql >> TableLoad_Main.sql
type .\TableLoad_31_High_Noon.sql >> TableLoad_Main.sql
type .\TableLoad_32_Long_Arm_of_the_Law.sql >> TableLoad_Main.sql
type .\TableLoad_33_Loot.sql >> TableLoad_Main.sql
type .\TableLoad_41_Utilities.sql >> TableLoad_Main.sql
