--Table Load 1
--RRI
--Keywords
/*Apprentice, The 					--Index   0*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Apprentice, The', 		'When this Raider is part of a Showdown, it may choose one Sheriff or Marshal. The chosen model does not participate in the fight.');
/*Bakusho Mondai 					--Index   1*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Bakusho Mondai', 		'During a Showdown, this Raider may chose one Raider on the same car. The chosen Raider must participate in the fight.');
/*Cactus Zak						--Index   2*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Cactus Zak', 			'Whenever you win a fight involving another Raider, score 1[$$].');
/*Canton Cobb						--Index   3*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Canton Cobb', 			'Before the game starts, draw and score or equip the top card of the Loot deck.');
/*Chuy					        	--Index   4*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Chuy', 				'Whenever you would be moved due to a fight, roll one die. If you roll a Q or higher, you aren''t moved. Whenever you are thrown Off the Train, you are put on the Caboose instead.');
/*Cowpuncher Candy		        	--Index   5*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Cowpuncher Candy', 	'You can use two weapons in a fight. During your turn, you may discard an equipped card to perform the same action for a third time on that turn.');
/*El Cola		    		    	--Index   6*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'El Cola', 				'You can''t equip weapons; discard them instead. If you have 2[$$] or more, then you may reroll two dice during Showdowns.');
/*Huckleberry		    	    	--Index   7*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Huckleberry', 			'During a Showdown, you may change one of your dice to an A after rerolls are resolved.');
/*John Grizzly		    	    	--Index   8*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'John Grizzly', 		'When you win a fight against the Lawbots they take one additional casualty.');
/*Josie Oakley		    	    	--Index   9*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Josie Oakley', 		'You may reroll one die during opposed Searches.');
/*JR Dallas		    	 		   	--Index   10*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'JR Dallas', 			'Once per turn, after taking a Showdown action, you may move or attempt to get on the train for free.');
/*Kid, The		    	   		 	--Index   11*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Kid, The', 			'You may reroll one die in Showdowns.');
/*Kingsman		    	   		 	--Index   12*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Kingsman', 			'When you lose a fight, you decide where you are moved instead of the winner.');
/*Mutha Superior		    	 	--Index   13*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Mutha Superior', 		'In a Showdown with Lawbots involved, you may reroll up to two dice.');
/*Pancho Perfecto		    	 	--Index   14*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Pancho Perfecto', 		'The first time you score [$$] from a Loot card in a turn, score an additional 1[$$].');
/*Pearl Heart		    		 	--Index   15*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Pearl Heart', 			'When you Search, before you choose a Loot token, look at a facedown Loot token on the car you are on.');
/*Rhinestone		    		 	--Index   16*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Rhinestone', 			'If the number of Lawbots on your car is equal to or less than the number of Raiders on the car, you may Search.');
/*Star Princess Candy			 	--Index   17*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Star Princess Candy', 	'Before boarding, this Raider may flip the car they are attempting to board. When boarding the flipped car, the Raider counts the car as one closer to the caboose for purposes of determining the hand rank needed to board.');
/*Steelhorse Candy			 		--Index   18*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Steelhorse Candy', 	'Whenever you perform a move action you may move 2 cars instead of 1.<br><br>If you would be thrown off of the train, you are moved 3 cars towards the caboose instead.');
/*Swordmage Acolyte			 		--Index   19*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Swordmage Acolyte', 	'When you target a Raider with a Showdown action you may move both models one car before any other Raider may decide to participate in the fight.');
/*Tazak Geronimo			 		--Index   20*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Tazak Geronimo', 		'When you win a fight against other Raiders, you may throw one of them Off the Train.');
/*Thorne			 				--Index   21*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Thorne', 				'In a Showdown that involves another Raider, you may roll one additional die.');
/*Typhoon			 				--Index   22*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Typhoon', 				'When you make three of a kind or higher in a fight, your final hand rank is increased by one.');
/*Umbra, PHD, Dr			 		--Index   23*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Umbra, PHD, Dr', 		'Whenever you destroy a Lawbot, you may draw and score a Loot card instead of scoring [$$] for destroying the Lawbot.');
/*Whistlin Pete				 		--Index   24*/ 		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Whistlin Pete', 		'After you Search, roll a die. If you roll a Q or higher score 1[$$].');

/*Lawbot					 		--Index   25*/		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Lawbot', 				'If a Raider destroys a Lawbot, the Raider receives [$$] as follows:<br><br>Deputy = 1[$$]<br>Sheriff = 2[$$]<br>Marshal = 3[$$]<br><br>All of the Lawbots on a train car fight as a team, so only roll once for all of them.');

/*Deputy					 		--Index   26*/		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Deputy', 				'');
/*Sheriff					 		--Index   27*/		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Sheriff', 				'If a group of Lawbots includes at least one Sheriff, then they may reroll one of their dice in a fight.');
/*Marshal					 		--Index   28*/		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Marshal', 				'If a group of Lawbots includes at least one Marshal, then they may roll an addtional die in a fight.');

/*Cavalry Solider			 		--Index   29*/		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Cavalry Solider', 		'If a Raider starts their turn on a car, or moves onto a car during their turn, that has a Cavalry Soldier on it, then they may only perform the Move action once during that turn.  Cavalry Soldiers do not cause Lawbots to reroll one of their dice during a fight like normal Sheriffs.');
/*Cavalry Captain			 		--Index   30*/		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Cavalry Captain', 		'After determining the Dealer for a round, if a Cavalry Captain is on a car without any Raiders on it, move them and one other Lawbot of the lowest rank on the car with them one car towards the nearest Raiders.  The Dealer makes any decisions necessary to resolve this ability.  Cavalry Captains allow Lawbots to roll an addtional die during fights, jsut like normal Marshals.');

/*Palbearer					 		--Index   31*/		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Palbearer', 			'If a Raider is moved as a result of a fight while on the same car as a Pallbearer, one Pallbearer will move to the same car that the Raider moves to.  This can happen multiple times if multiple Raiders are moved due to the same fight.  Pallbearers do not allow Lawbots to reroll one of their dice during a fight like normal Sheriffs.');
/*Preacher					 		--Index   32*/		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Preacher', 			'If at least one Preacher is on the same car as a Raider who performs the Move action or is moved as the result of a fight, the Raider loses 1[$$].  Preachers do not allow Lawbots to roll an additional die during fights like normal Marshals.');

/*999						 		--Index   33*/		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', '999', 					'Put 999 on the car.  If 999 is already in play, then put one deputy on the car instead.  999 is a Marshal.  Additionally whenever Lawbots lose a fight while 999 is present with other Lawbots during the fight, 999 is moved to an adjacent car of the winner''s choice instead of the lowest ranking Lawbot being destroyed.  [$$] are still scored as though the lowest ranking Lawbot was destroyed.');
/*LT Deadeye				 		--Index   34*/		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Lt Deadeye', 			'Put Lt. Deadeye on the car.  If Lt. Deadeye is already in play put one Sheriff on the car instead.  Lt. Deadeye is a Sheriff.  Additionally, Raiders can''t Search while they are on cars that are adjacent to the car that Lt. Deadeye is on.');


/*Both Barrels				 		--Index   35*/		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Both Barrels', 		'Until the end of yoru turn, when Lawbots lose a fight destroy one additional Lawbot.  When Raiders lose a fight, they are thrown Off the Train instead of being moved.');
/*Crossfire					 		--Index   36*/		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Crossfire', 			'Until the end of your turn, if there is another Raider on the same car, roll one additional die in fights.');
/*Daring Acrobatics			 		--Index   37*/		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Daring Acrobatics', 	'You may move to any other car on the train.  If you do, you can''t take any Move actions this turn.');
/*Dead Man's Hand			 		--Index   38*/		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Dead Man''s Hand', 	'Until the end of your turn, if you make the lowest ranking hand in a fight, you win that fight.');
/*Dead Or Alive				 		--Index   39*/		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Dead Or Alive', 		'Lawbots may reroll up to one die in fights until the end of the round.');
/*Fan the Hammer			 		--Index   40*/		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Fan the Hammer', 		'Whenever you take the Showdown action this tunr, you may Showdown twice in a row as part of the same action.');
/*Fire Main Thrusters		 		--Index   41*/		insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('RRI', 'Default', 'Fire Main Thrusters', 	'Discard the top card of the High Noon deck.');

