--SDE
--1.0 Custom
--Abilities


/*Buckaroo 									--Index 2170*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Buckaroo', 'Action', 'Offense', 2, 0, -1, 'Wave 1, DANGEROUS, IMMUNE: Mob');
/*Stampede 									--Index 2171*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Stampede', 'Action', 'Offense', 3, 0, 0, 'ATT vs. DEX, TRAMPLE');
/*Haymaker 									--Index 2172*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Haymaker', 'Action', 'Offense', 3, 0, 0, '+1R ATT, Stun');
/*Applesauce								--Index 2173*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Applesauce', 'Potion', 'Support', 1, -1, 0, '+1B ARM');

/*Mistwalker								--Index 2174*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Mistwalker', 'Action', 'Offense', 2, 0, -1, 'Cross 2, Dangerous');
/*Lunar Blade								--Index 2175*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Lunar Blade', 'Action', 'Offense', 2, 0, 1, '+1R ATT, Pacify, Slow');
/*Second Wind								--Index 2176*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Second Wind', 'Action', 'Support', 2, -1, 0, 'Heal 1, Remedy');
/*Talent Blaster							--Index 2177*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Talent Blaster', 'Potion', 'Support', 1, -1, 0, '+1B ATT, ARM, WILL, DEX');

/*Stand Fast!								--Index 2178*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Stand Fast!', 'Action', 'Support', 1, -1, -1, 'AUGMENT, Aura 1, Heal 1, Remedy');
/*Smite										--Index 2179*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Smite', 'Action', 'Offense', 1, 0, 1, 'Push 1');
/*Anesthesia								--Index 2180*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Anesthesia', 'Potion', 'Support', 1, -1, 0, '+3B ARM');

/*Summoning									--Index 2181*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Summoning', 'Action', 'Support', 1, -1, 1, 'Place a Wyrmling adjacent.  May not be used again while the Wyrmling remains in play.');
/*Direct									--Index 2182*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Direct', 'Action', 'Support', 1, -1, -1, 'Activate the Wyrmling.');
/*Bolster									--Index 2183*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Bolster', 'Action', 'Support', 1, -1, -1, 'The Wyrmling gains the benefits of your equipped Loot and Treasure.');
/*Coals										--Index 2184*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Coals', 'Potion', 'Support', 1, 3, 0, '+1R WILL, Spray 3, FIRE (Wyrmling may use only this potion)');

/*Sexy Dance								--Index 2185*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Sexy Dance', 'Action', 'Support', 1, -1, 6, '6RG, COMPEL 3, DEX vs. WILL');
/*Kaleidoscope								--Index 2186*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Kaleidoscope', 'Action', 'Offense', 2, 0, 0, '+3 ATT, PACIFY');
/*Whirling Dervish							--Index 2187*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Whirling Dervish', 'Action', 'Offense', 2, 0, -1, 'Wave 1');
/*Caffeine Pills							--Index 2188*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Caffeine Pills', 'Potion', 'Support', 1, -1, 0, '+5MO');

/*Rally Cry									--Index 2189*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Rally Cry', 'Action', 'Support', 1, -1, -1, 'AUGMENT, Aura 3, +1B ATT');
/*Aimed Strike								--Index 2190*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Aimed Strike', 'Action', 'Offense', 2, 0, 0, '+1R ATT, KNOCKDOWN');
/*Flash Bomb								--Index 2191*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Flash Bomb', 'Potion', 'Support', 1, -1, 4, '4RG, IMMOBILE, WEAK');

/*Flecha Envenenada							--Index 2192*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Flecha Envenenada', 'Action', 'Offense', 2, 4, 1, '+1G DEX, POISON');
/*Petrificar								--Index 2193*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Petrificar', 'Action', 'Offense', 2, 0, -1, 'Wave 2, IMMOBILE');
/*Miedo										--Index 2194*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Miedo', 'Action', 'Support', 1, -1, 1, 'SLOW');

/*Embestida									--Index 2195*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Embestida', 'Action', 'Offense', 2, 0, 1, '+1G ATT, MASSIVE DAMAGE');
/*Aplastar									--Index 2196*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Aplastar', 'Action', 'Offense', 2, 0, -1, 'Wave 2');
/*Terror									--Index 2197*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Terror', 'Action', 'Support', 1, -1, 1, 'IMMOBILE');

/*Garra Mortal								--Index 2198*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Garra Mortal', 'Action', 'Offense', 2, 0, 1, '+1R ATT, MASSIVE DAMAGE');
/*Bola de Fuego								--Index 2199*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Bola de Fuego', 'Action', 'Offense', 2, 0, -1, 'Lance 4');
/*Picadura									--Index 2200*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Picadura', 'Action', 'Support', 1, -1, 1, 'IMMOBILE');

/*Rayo Mortal								--Index 2201*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Rayo Mortal', 'Action', 'Offense', 2, 4, 1, '+1G DEX, KNOCKDOWN');
/*Pared de Fuego							--Index 2202*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Pared de Fuego', 'Action', 'Offense', 1, 0, -1, 'SPRAY 3');

/*Assult									--Index 2203*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Assult', 'Action', 'Offense', 1, 0, 1, '+1B if an enemy is suffering the from the effect of KNOCKDOWN.');

/*Slick										--Index 2204*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Slick', 'Action', 'Offense', 1, 3, 1, '+1B WILL.  KNOCKDOWN.');

/*Tail Stab									--Index 2205*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Tail Stab', 'Action', 'Offense', 2, 0, 2, '+1R WILL.  KNOCKDOWN.');

/*Web Shot									--Index 2206*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Tail Stab', 'Action', 'Offense', 1, 4, 4, '4RG, +1B DEX, SLOW.');

/*Finding Strays							--Index 2207*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Finding Strays', 'Action', 'Offense', 2, 3, 1, '+1B WILL, Summon');
/*Can I Keep Him?							--Index 2208*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Can I Keep Him?', 'Action', 'Offense', 2, 3, 1, '+1R WILL vs. WILL, Tame');
/*Liquid Courage							--Index 2209*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Liquid Courage', 'Potion', 'Support', 1, -1, 0, '+1B WILL');

/*I am NOT a man!							--Index 2210*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'I am NOT a man!', 'Action', 'Offense', 2, 0, 2, '+1R ATT, Massive Damage');
/*Wanna Wrassle?							--Index 2211*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Wanna Wrassle?', 'Action', 'Offense', 1, 0, 2, '+1B ATT, Stun');
/*Kegus Universalis							--Index 2212*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Kegus Universalis', 'Potion', 'Support', 1, -1, 0, '+1B ARM, Immune: Fragile');

/*Subdue									--Index 2213*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Subdue', 'Action', 'Offense', 2, 0, 8, 'Ranged 8, WEAK');
/*Supressing Fire							--Index 2214*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Supressing Fire', 'Action', 'Offense', 2, 0, 2, 'Ranged 2, Burst 1, DANGEROUS');
/*Sunburst									--Index 2215*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Sunburst', 'Potion', 'Offense', 1, 0, -1, 'Wave 2, FIRE, FRAGILE, DANGEROUS');

/*Takedown									--Index 2216*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Takedown', 'Action', 'Offense', 1, 0, 1, 'KNOCKDOWN');
/*Sunder									--Index 2217*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Sunder', 'Action', 'Offense', 2, 0, 1, 'FRAGILE, WEAK');
/*Styigan Root								--Index 2218*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Styigan', 'Potion', 'Offense', 1, -1, 0, 'POISON');

/*Sword of Vulcanis							--Index 2219*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Sword of Vulcanis', 'Action', 'Offense', 1, 0, 3, 'RANGE 3, PULL 3');
/*Shield Smash								--Index 2220*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Shield Smash', 'Action', 'Offense', 2, 0, 1, '+1R ATT, KNOCKDOWN');
/*Heroic Scream								--Index 2221*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Heroic Scream', 'Action', 'Support', 1, -1, -1, 'AUGMENT, SPRAY 3, REMEDY');
/*Elixir of Fire							--Index 2222*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Elixir of Fire', 'Potion', 'Support', 1, -1, 0, '+1R ATT, FIRE');

/*Lotus Blossom								--Index 2223*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Lotus Blossom', 'Action', 'Offense', 2, 0, 3, 'WAVE 1');
/*Chakra Blast								--Index 2224*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Chakra Blast', 'Action', 'Support', 2, -1, 1, 'WAVE 2, PUSH 2, WILL vs. WILL');
/*Instant Karma								--Index 2225*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Instant Karma', 'Action', 'Support', 1, -1, -1, 'For every wound the Monk takes, roll 1B.  For every star rolled the attacking model takes one wound.');
/*Inner Peace								--Index 2226*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Inner Peace', 'Potion', 'Support', 1, -1, 0, '+1R WILL');

/*Arcane Fury								--Index 2227*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Arcane Fury', 'Action', 'Support', 1, -1, 0, '-1R ARM, +1R WILL, FIRE');
/*Blizzard									--Index 2228*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Blizzard', 'Action', 'Offense', 2, 3, 8, 'BURST 1, COMPEL 3');
/*Instant Karma								--Index 2229*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Freeze the Heartblood', 'Action', 'Offense', 2, 3, 8, '+2B WILL, FRAGILE');
/*Inner Peace								--Index 2230*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Ice Queen', 'Potion', 'Support', 1, -1, 0, '+2B ARM, Backlash');

/*Swash th'Bucks!							--Index 2231*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Swash th''Bucks!', 'Action', 'Offense', 1, -1, -1, 'AUGMENT, AURA 3, +1B ATTACK');
/*Nyahaha Taunt								--Index 2232*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Nyahaha Taunt', 'Action', 'Offense', 1, -1, 3, 'RANGE 3, COMPEL 3, WILL vs. WILL');
/*Cap'n's Grog								--Index 2233*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Cap''s Grog''', 'Potion', 'Support', 1, -1, 0, '+1B ARM, STURDY');

/*Confetti Bomb								--Index 2234*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Confetti Bomb', 							'Action', 'Support', 1, -1, 8, 'MISSILE 8, BURST 1, SMOKE');
/*Super-Sticky-Double-Bubble Bubble-Gum		--Index 2235*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Super-Sticky-Double-Bubble Bubble-Gum',	'Action', 'Support', 2, -1, -1, 'SPRAY 4, SLOW');
/*Pinkie Cannon								--Index 2236*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Pinkie Cannon',							'Action', 'Offense', 3, 0, -1, 'SPRAY 3');
/*Pinkie Logic								--Index 2237*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Pinkie Logic',							'Potion', 'Support', 1, -1, 0, 'Attacking models suffer PACIFY');

/*Aura of Love								--Index 2238*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Aura of Love',							'Action', 'Support', 2, -1, -1, '+1R WILL, WAVE 2, PACIFY');
/*The Power of Love							--Index 2239*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'The Power of Love',						'Action', 'Support', 1, -1, -1, 'AUGMENT, AURA 1, HEAL 1, REMEDY');
/*Loving Care								--Index 2240*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Loving Care',								'Potion', 'Support', 1, -1, 0, '+1R ARM, HEAL 1');

/*Double Dash								--Index 2241*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Aura of Love',							'Action', 'Support', 1, -1, 0, '+1MO');
/*Sonic Rainbow								--Index 2242*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'The Power of Love',						'Action', 'Offense', 3, 0, -1, 'SWEEP 3, DANGEROUS, DEX vs. ARM, Overhead');
/*Twenty Percent Cooler						--Index 2243*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Loving Care',								'Potion', 'Support', 1, -1, 0, '+1B');





