--SDE
--1.0 Custom
--Abilities


/*Buckaroo 									--Index 2080*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Buckaroo', 'Action', 'Offense', 2, 0, -1, 'Wave 1, DANGEROUS, IMMUNE: Mob');
/*Stampede 									--Index 2081*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Stampede', 'Action', 'Offense', 3, 0, 0, 'ATT vs. DEX, TRAMPLE');
/*Haymaker 									--Index 2082*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Haymaker', 'Action', 'Offense', 3, 0, 0, '+1R ATT, Stun');
/*Applesauce								--Index 2083*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Applesauce', 'Potion', 'Support', 1, -1, 0, '+1B ARM');

/*Mistwalker								--Index 2084*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Mistwalker', 'Action', 'Offense', 2, 0, -1, 'Cross 2, Dangerous');
/*Lunar Blade								--Index 2085*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Lunar Blade', 'Action', 'Offense', 2, 0, 1, '+1R ATT, Pacify, Slow');
/*Second Wind								--Index 2086*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Second Wind', 'Action', 'Support', 2, -1, 0, 'Heal 1, Remedy');
/*Talent Blaster							--Index 2087*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Talent Blaster', 'Potion', 'Support', 1, -1, 0, '+1B ATT, ARM, WILL, DEX');

/*Stand Fast!								--Index 2088*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Stand Fast!', 'Action', 'Support', 1, -1, -1, 'AUGMENT, Aura 1, Heal 1, Remedy');
/*Smite										--Index 2089*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Smite', 'Action', 'Offense', 1, 0, 1, 'Push 1');
/*Anesthesia								--Index 2090*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Anesthesia', 'Potion', 'Support', 1, -1, 0, '+3B ARM');

/*Summoning									--Index 2091*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Summoning', 'Action', 'Support', 1, -1, 1, 'Place a Wyrmling adjacent.  May not be used again while the Wyrmling remains in play.');
/*Direct									--Index 2092*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Direct', 'Action', 'Support', 1, -1, -1, 'Activate the Wyrmling.');
/*Bolster									--Index 2093*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Bolster', 'Action', 'Support', 1, -1, -1, 'The Wyrmling gains the benefits of your equipped Loot and Treasure.');
/*Coals										--Index 2094*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Coals', 'Potion', 'Support', 1, 3, 0, '+1R WILL, Spray 3, FIRE (Wyrmling may use only this potion)');

/*Sexy Dance								--Index 2095*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Sexy Dance', 'Action', 'Support', 1, -1, 6, '6RG, COMPEL 3, DEX vs. WILL');
/*Kaleidoscope								--Index 2096*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Kaleidoscope', 'Action', 'Offense', 2, 0, 0, '+3 ATT, PACIFY');
/*Whirling Dervish							--Index 2097*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Whirling Dervish', 'Action', 'Offense', 2, 0, -1, 'Wave 1');
/*Caffeine Pills							--Index 2098*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Caffeine Pills', 'Potion', 'Support', 1, -1, 0, '+5MO');

/*Rally Cry									--Index 2099*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Rally Cry', 'Action', 'Support', 1, -1, -1, 'AUGMENT, Aura 3, +1B ATT');
/*Aimed Strike								--Index 2100*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Aimed Strike', 'Action', 'Offense', 2, 0, 0, '+1R ATT, KNOCKDOWN');
/*Flash Bomb								--Index 2101*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Flash Bomb', 'Potion', 'Support', 1, -1, 4, '4RG, IMMOBILE, WEAK');

/*Flecha Envenenada							--Index 2102*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Flecha Envenenada', 'Action', 'Offense', 2, 4, 1, '+1G DEX, POISON');
/*Petrificar								--Index 2103*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Petrificar', 'Action', 'Offense', 2, 0, -1, 'Wave 2, IMMOBILE');
/*Miedo										--Index 2104*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Miedo', 'Action', 'Support', 1, -1, 1, 'SLOW');

/*Embestida									--Index 2105*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Embestida', 'Action', 'Offense', 2, 0, 1, '+1G ATT, MASSIVE DAMAGE');
/*Aplastar									--Index 2106*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Aplastar', 'Action', 'Offense', 2, 0, -1, 'Wave 2');
/*Terror									--Index 2107*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Terror', 'Action', 'Support', 1, -1, 1, 'IMMOBILE');

/*Garra Mortal								--Index 2108*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Garra Mortal', 'Action', 'Offense', 2, 0, 1, '+1R ATT, MASSIVE DAMAGE');
/*Bola de Fuego								--Index 2109*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Bola de Fuego', 'Action', 'Offense', 2, 0, -1, 'Lance 4');
/*Picadura									--Index 2110*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Picadura', 'Action', 'Support', 1, -1, 1, 'IMMOBILE');

/*Rayo Mortal								--Index 2111*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Rayo Mortal', 'Action', 'Offense', 2, 4, 1, '+1G DEX, KNOCKDOWN');
/*Pared de Fuego							--Index 2112*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Pared de Fuego', 'Action', 'Offense', 1, 0, -1, 'SPRAY 3');

/*Assult									--Index 2113*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Assult', 'Action', 'Offense', 1, 0, 1, '+1B if an enemy is suffering the from the effect of KNOCKDOWN.');

/*Slick										--Index 2114*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Slick', 'Action', 'Offense', 1, 3, 1, '+1B WILL.  KNOCKDOWN.');

/*Tail Stab									--Index 2115*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Tail Stab', 'Action', 'Offense', 2, 0, 2, '+1R WILL.  KNOCKDOWN.');

/*Web Shot									--Index 2116*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Web Shot', 'Action', 'Offense', 1, 4, 4, '4RG, +1B DEX, SLOW.');

/*Finding Strays							--Index 2117*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Finding Strays', 'Action', 'Offense', 2, 3, 1, '+1B WILL, Summon');
/*Can I Keep Him?							--Index 2118*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Can I Keep Him?', 'Action', 'Offense', 2, 3, 1, '+1R WILL vs. WILL, Tame');
/*Liquid Courage							--Index 2119*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Liquid Courage', 'Potion', 'Support', 1, -1, 0, '+1B WILL');

/*I am NOT a man!							--Index 2120*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'I am NOT a man!', 'Action', 'Offense', 2, 0, 2, '+1R ATT, Massive Damage');
/*Wanna Wrassle?							--Index 2121*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Wanna Wrassle?', 'Action', 'Offense', 1, 0, 2, '+1B ATT, Stun');
/*Kegus Universalis							--Index 2122*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Kegus Universalis', 'Potion', 'Support', 1, -1, 0, '+1B ARM, Immune: Fragile');

/*Subdue									--Index 2123*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Subdue', 'Action', 'Offense', 2, 0, 8, 'Ranged 8, WEAK');
/*Supressing Fire							--Index 2124*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Supressing Fire', 'Action', 'Offense', 2, 0, 2, 'Ranged 2, Burst 1, DANGEROUS');
/*Sunburst									--Index 2125*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Sunburst', 'Potion', 'Offense', 1, 0, -1, 'Wave 2, FIRE, FRAGILE, DANGEROUS');

/*Takedown									--Index 2126*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Takedown', 'Action', 'Offense', 1, 0, 1, 'KNOCKDOWN');
/*Sunder									--Index 2127*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Sunder', 'Action', 'Offense', 2, 0, 1, 'FRAGILE, WEAK');
/*Styigan Root								--Index 2128*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Styigan', 'Potion', 'Offense', 1, -1, 0, 'POISON');

/*Sword of Vulcanis							--Index 2129*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Sword of Vulcanis', 'Action', 'Offense', 1, 0, 3, 'RANGE 3, PULL 3');
/*Shield Smash								--Index 2130*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Shield Smash', 'Action', 'Offense', 2, 0, 1, '+1R ATT, KNOCKDOWN');
/*Heroic Scream								--Index 2131*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Heroic Scream', 'Action', 'Support', 1, -1, -1, 'AUGMENT, SPRAY 3, REMEDY');
/*Elixir of Fire							--Index 2132*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Elixir of Fire', 'Potion', 'Support', 1, -1, 0, '+1R ATT, FIRE');

/*Lotus Blossom								--Index 2133*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Lotus Blossom', 'Action', 'Offense', 2, 0, 3, 'WAVE 1');
/*Chakra Blast								--Index 2134*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Chakra Blast', 'Action', 'Support', 2, -1, 1, 'WAVE 2, PUSH 2, WILL vs. WILL');
/*Instant Karma								--Index 2135*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Instant Karma', 'Action', 'Support', 1, -1, -1, 'For every wound the Monk takes, roll 1B.  For every star rolled the attacking model takes one wound.');
/*Inner Peace								--Index 2136*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Inner Peace', 'Potion', 'Support', 1, -1, 0, '+1R WILL');

/*Arcane Fury								--Index 2137*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Arcane Fury', 'Action', 'Support', 1, -1, 0, '-1R ARM, +1R WILL, FIRE');
/*Blizzard									--Index 2138*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Blizzard', 'Action', 'Offense', 2, 3, 8, 'BURST 1, COMPEL 3');
/*Instant Karma								--Index 2139*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Freeze the Heartblood', 'Action', 'Offense', 2, 3, 8, '+2B WILL, FRAGILE');
/*Inner Peace								--Index 2140*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Ice Queen', 'Potion', 'Support', 1, -1, 0, '+2B ARM, Backlash');

/*Swash th'Bucks!							--Index 2141*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Swash th''Bucks!', 'Action', 'Offense', 1, -1, -1, 'AUGMENT, AURA 3, +1B ATTACK');
/*Nyahaha Taunt								--Index 2142*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Nyahaha Taunt', 'Action', 'Offense', 1, -1, 3, 'RANGE 3, COMPEL 3, WILL vs. WILL');
/*Cap'n's Grog								--Index 2143*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Cap''s Grog''', 'Potion', 'Support', 1, -1, 0, '+1B ARM, STURDY');

/*Confetti Bomb								--Index 2144*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Confetti Bomb', 							'Action', 'Support', 1, -1, 8, 'MISSILE 8, BURST 1, SMOKE');
/*Super-Sticky-Double-Bubble Bubble-Gum		--Index 2145*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Super-Sticky-Double-Bubble Bubble-Gum',	'Action', 'Support', 2, -1, -1, 'SPRAY 4, SLOW');
/*Pinkie Cannon								--Index 2146*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Pinkie Cannon',							'Action', 'Offense', 3, 0, -1, 'SPRAY 3');
/*Pinkie Logic								--Index 2147*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Pinkie Logic',							'Potion', 'Support', 1, -1, 0, 'Attacking models suffer PACIFY');

/*Aura of Love								--Index 2148*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Aura of Love',							'Action', 'Support', 2, -1, -1, '+1R WILL, WAVE 2, PACIFY');
/*The Power of Love							--Index 2149*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'The Power of Love',						'Action', 'Support', 1, -1, -1, 'AUGMENT, AURA 1, HEAL 1, REMEDY');
/*Loving Care								--Index 2150*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Loving Care',								'Potion', 'Support', 1, -1, 0, '+1R ARM, HEAL 1');

/*Double Dash								--Index 2151*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Aura of Love',							'Action', 'Support', 1, -1, 0, '+1MO');
/*Sonic Rainbow								--Index 2152*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'The Power of Love',						'Action', 'Offense', 3, 0, -1, 'SWEEP 3, DANGEROUS, DEX vs. ARM, Overhead');
/*Twenty Percent Cooler						--Index 2153*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Loving Care',								'Potion', 'Support', 1, -1, 0, '+1B');

/*Defensive Ball Curl						--Index 2154*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Defensive Ball Curl',						'Action', 'Support', 1, -1, 0, 'AUGMENT +2 ARM');
/*Puncturing Taunt							--Index 2155*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Puncturing Taunt',						'Action', 'Support', 2, -1, -1, 'All enemies adjacent to Rammus must attack Rammus.  Enemies that attack Rammus take a 1R damage roll.');

/*Rought Cut								--Index 2156*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Rought Cut',								'Action', 'Support', 1, 3, 8, 'MAGIC 8, DIFFICULT TERRAIN');
/*Crystalize								--Index 2157*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Crystalize',								'Action', 'Support', 2, 3, 8, 'MAGIC 8, FORM CRYSTAL');
/*Shatter									--Index 2158*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Shatter',									'Action', 'Offense', 1, 3, 8, 'MAGIC 8, BURST 1, SHATTER');
/*Crystal Armour							--Index 2159*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Crystal Armour',							'Potion', 'Support', 1, -1, 0, '+1ST ARM');

/*Disarm									--Index 2160*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Disarm',									'Action', 'Offense', 2, 0, -1, '+1R ATT, WEAK');
/*Lunge										--Index 2161*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Lunge',									'Action', 'Offense', 1, 0, 8, '+1G ATT, FRAGILE');
/*Hero's Sacrifice							--Index 2162*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Hero''s Sacrifice',						'Potion', 'Support', 1, -1, -1, 'Remove a wound counter from a Hero and add a wound counter to affected Hero');

/*Hardened Scales							--Index 2163*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Hardened Scales',							'Action', 'Support', 2, -1, 0, 'On defense rolls, rolls an extra 1B');
/*Flame Breath								--Index 2164*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Flame Breath',							'Potion', 'Support', 1, 0, 10, 'RANGE 10, DANGEROUS');

/*Lunging Slash								--Index 2165*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Lunging Slash',							'Action', 'Offense', 1, 0, -1, 'LANCE 3');
/*Vorpal Strike								--Index 2166*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Vorpal Strike',							'Action', 'Offense', 3, 0, 1, '+1G ATT, MASSIVE DAMAGE');
/*Invulnerable								--Index 2167*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Invulnerable',							'Potion', 'Support', 1, -1, 0, 'IMMUNE: STATUS EFFECTS, REMEDY');

/*Fend										--Index 2168*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Fend',									'Action', 'Offense', 2, 0, -1, 'CROSS 1, KNOCKDOWN');
/*Lightning Fury							--Index 2169*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Lightning Fury',							'Action', 'Offense', 2, 4, -1, 'MISSILE 6, SPRAY 3, +1B DEX.  The Spray effect only occurs if the model targeted is wounded and the area affected starts with the square the targeted model is on.');
/*Dinosaur Eggs								--Index 2170*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Dinosaur Eggs',							'Potion', 'Support', 1, -1, 0, 'DODGE');

/*Telekinesis								--Index 2171*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Telekinesis',								'Action', 'Support', 1, -1, 8, 'COMPEL 3');
/*Friend Zone								--Index 2172*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Friend Zone',								'Action', 'Support', 3, -1, 8, 'AUGMENT, BURST 1, HEAL 1');
/*Twilight Sparkleburst						--Index 2173*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Twilight Sparkleburst',					'Action', 'Offense', 3, 3, 8, 'BURST 1');
/*Studious									--Index 2174*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Studious',								'Potion', 'Support', 1, -1, 0, 'LUCK');

/*The Wolf									--Index 2175*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Wolf, The',								'Action', 'Offense', 3, 0, -1, 'After every square you move this turn you can make one melee attack.  Each attack after the first adds an additional 1B to the dice roll.  You cannot step in the same square twice.  Your ARM is reduced to 1B until next activation irrespective of equipment.  Auras still take affect however.<br><br>The Wolf cannot use potions, but can benefit from the effect of other''s potions.');

/*Toxic Breath								--Index 2176*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Toxic Breath',							'Action', 'Offense', 2, 0, -1, 'SPRAY 3, POISON');
/*Chomp										--Index 2177*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Chomp',									'Action', 'Offense', 2, 0, 1, '+1G MASSIVE DAMAGE');

/*Wirlwind of Bones							--Index 2178*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Wirlwind of Bones',						'Action', 'Support', 1, -1, -1, 'AURA 4, RAISE');
/*Powerball									--Index 2179*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Powerball',								'Action', 'Offense', 1, 3, 6, '+1R WILL');
/*Now You Don't								--Index 2180*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Now You Don''t',							'Potion', 'Support', 1, -1, 0, 'TELEPORT');

/*Big Bash									--Index 2181*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Big Bash',								'Action', 'Offense', 2, 0, 2, '+1G ATT, MASSIVE DAMAGE');
/*Strangle Hold								--Index 2182*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Strangle Hold',							'Action', 'Offense', 2, 0, 2, 'IMMOBILE, WEAK');

/*Chaos Hammer								--Index 2183*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Chaos Hammer',							'Action', 'Offense', 2, 0, -1, 'SWEEP 2, KNOCKDOWN');
/*Boom										--Index 2184*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Boom',									'Action', 'Offense', 3, 0, 2, '+1R ATT, MASSIVE DAMAGE');

/*Precision Cut								--Index 2185*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Precision Cut',							'Action', 'Offense', 2, 4, 1, '+1B DEX, MASSIVE DAMAGE');
/*Ice Blade									--Index 2186*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Ice Blade',								'Action', 'Offense', 2, 0, 1, '+1B ATT, IMMOBILE');
/*War Cry									--Index 2187*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'War Cry',									'Action', 'Support', 2, -1, -1, 'AUGMENT, AURA 1, +1R ATT');
/*Spoils of War								--Index 2188*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Spoils of War',							'Action', 'Support', 2, -1, 0, 'Draw and equip 1 Relic card.');

/*Fire Breath								--Index 2189*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Fire Breath',								'Action', 'Offense', 2, 0, -1, 'SWEEP 4, FIRE');
/*Butt Stomp								--Index 2190*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Butt Stomp',								'Action', 'Offense', 2, 0, -1, 'WAVE 2, PUSH 1, KNOCKDOWN');

/*Shapeshift: Brown Wizard					--Index 2191*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Shapeshift: Brown Wizard',				'Action', 'Support', 1, -1, 0, 'Remove both Brown Boar models from the board, and place the Brown Wizard model within 1 square of where either Brown Boar was before it was removed.');
/*Tusks										--Index 2192*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Tusks',									'Action', 'Offense', 2, 0, 1, '+1G ATT, FRAGILE');

/*Shapeshift: Brown Boars					--Index 2193*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Shapeshift: Brown Boars',					'Action', 'Support', 1, -1, 0, 'Remove the Brown Wizard model from the board, and place both Brown Boar models where or adjacent to where the Brown Wizard model was.');
/*Spectral Bats								--Index 2194*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Spectral Bats',							'Action', 'Offense', 2, 3, 8, 'MAGIC 8, BURST 5');
/*Spitting Cobra							--Index 2195*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Spitting Cobra',							'Action', 'Offense', 2, 3, -1, 'MAGIC, LANCE 8');
/*Disorientate								--Index 2196*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Disorientate',							'Action', 'Offense', 3, 3, 6, 'MAGIC 6.  Status Effect: Enemy can only move diagonally.');

/*Dual Weapons								--Index 2197*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Dual Weapons',							'Action', 'Offense', 2, 0, -1, 'WAVE 1 ATT');
/*Lightning									--Index 2198*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Lightning',								'Action', 'Offense', 1, 4, 8, 'BURST 1 DEX');
/*Extreme Aggression						--Index 2199*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Extreme Aggression',						'Action', 'Offense', 2, 0, -1, 'SWEEP 2');

/*Charge									--Index 2200*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Charge',									'Action', 'Offense', 2, 0, -1, '(Only if have moved more than/equal to half speed i.e. 5 spaces) KNOCKDOWN');
/*Lightning									--Index 2201*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Lightning',								'Action', 'Offense', 1, 4, 8, 'BURST 1');
/*Backstab									--Index 2202*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Backstab',								'Action', 'Offense', 3, 0, 1, 'MASSIVE DAMAGE +1B ATT');

/*Red Dragon								--Index 2203*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Red Dragon',								'Action', 'Offense', 1, 0, -1, 'LANCE 6, FIRE');
/*Blue Dragon								--Index 2204*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Blue Dragon',								'Action', 'Offense', 2, 0, -1, 'CROSS 5, STUN');
/*Green Dragon								--Index 2205*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Green Dragon',							'Action', 'Offense', 2, 0, -1, 'SPRAY 3, POISON');
/*Black Dragon								--Index 2206*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Black Dragon',							'Action', 'Offense', 1, 0, -1, 'BURST 1, FRAGILE');
/*White Dragon								--Index 2207*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'White Dragon',							'Action', 'Offense', 2, 0, -1, 'SPRAY 4, COLD');

/*Spin Attack								--Index 2208*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Spin Attack',								'Action', 'Offense', 1, 0, -1, 'Sweep');
/*Summon Rabite								--Index 2209*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Summon Rabite',							'Action', 'Support', 1, 3, -1, 'Roll WILL, if at least 1 star is rolled, place a Rabit adjacent to Rabbillion.');

/*Chomp										--Index 2210*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Chomp',									'Action', 'Offense', 1, 0, 1, '+1R');

/*Shieldwall								--Index 2211*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Shieldwall',								'Action', 'Support', 1, -1, 0, 'AUGMENT, AURA 1, +1B ARM');

/*Stand Ready!								--Index 2212*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Stand Ready!',							'Action', 'Support', 1, -1, 1, 'The Slime is ready to combine.  If four slimes are adjacent to each other and have used this Action, remove them from play and replace them with a Dukeslime, which is activated immediately.');

/*Absorb									--Index 2213*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Absorb',									'Action', 'Support', 1, -1, 1, 'Steal');

/*Slime Time								--Index 2214*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Slime Time',								'Action', 'Support', 1, -1, -1, 'AUGMENT, AURA 3, +1 ARM to Slimes');
/*Puff Up!									--Index 2215*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Puff Up!',								'Action', 'Offense', 2, 0, -1, 'Sweep 1, KNOCKDOWN');

/*Heal										--Index 2216*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Heal',									'Action', 'Support', 1, -1, 3, 'RANGE 3, HEAL 1');

/*Frizz										--Index 2217*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Frizz',									'Action', 'Offense', 1, 3, 6, 'MAGIC 6, FIRE, +1B WILL');

/*Explode									--Index 2218*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Explode',									'Action', 'Offense', 2, 0, -1, 'WAVE 2, +1G ATT, destroy Bob-omb.  Remove the model from the map, but do not advance the Power Gauge.');

/*Head Bonk									--Index 2219*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Head Bonk',								'Action', 'Offense', 2, 0, 2, 'REACH 2, +1B');

/*Shell Toss								--Index 2220*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Shell Toss',								'Action', 'Offense', 2, 0, -1, 'LANCE 4');

/*Pistol Barrage							--Index 2221*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Shell Toss',								'Action', 'Offense', 2, 0, -1, 'LANCE 4');
/*High Tide									--Index 2222*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Explore', 'Shell Toss',								'Action', 'Offense', 2, 0, -1, 'LANCE 4');

