--SDE
--2.0.3
--Abilities


/*Freezing Wind														--Index 2223*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 'Freezing Wind', 									'Action', 'Support', 	0, -1, -1, 'Wave 3, Push 3, ICE, KNOCKDOWN'); --!!!
/*Frostbite															--Index 2224*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 'Frostbite', 										'Action', 'Support', 	0, -1, -1, 'Wave 3, BANE, POISON, ICE'); --!!!
/*Dun Dun, Nom Nom													--Index 2225*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 'Dun Dun, Nom Nom', 								'Action', 'Offense', 	1, 1, 1, '1SW, POUNCE.');
/*Top Sail Pounce													--Index 2226*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 'Top Sail Pounce', 								'Action', 'Offense', 	2, 4, 1, '1MI, +1R DEX, POUNCE');
/*Sanguine Blade													--Index 2227*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 'Sanguine Blade', 								'Action', 'Offense', 	2, 4, 1, '1MI, +3B DEX, HEART STRIKE');
/*Epic Duel															--Index 2228*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 'Epic Duel', 										'Action', 'Support', 	1, -1, 6, '6RG, Until the affected model inflicts a wound on Dread Scarlett, it may only target Dread Scarlett.');
/*Run Red															--Index 2229*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 'Run Red', 										'Action', 'Support', 	1, -1, -1, 'All other friendly Pirates on this tile may immediately move two squares.');
/*Crimson Port														--Index 2230*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Crimson Port', 									'Potion', 'Emergency', 	1, -1, 0, 'AUGMENT, HEAL 1, BACKSTABBER');
/*																	--Index 2231*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', 														'', '', 	-1, -1, -1, '');
/*																	--Index 2232*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', 														'', '', 	-1, -1, -1, '');
/*																	--Index 2233*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', 														'', '', 	-1, -1, -1, '');
/*																	--Index 2234*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', 														'', '', 	-1, -1, -1, '');
/*																	--Index 2235*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', 														'', '', 	-1, -1, -1, '');
/*																	--Index 2236*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', 														'', '', 	-1, -1, -1, '');
/*																	--Index 2237*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', 														'', '', 	-1, -1, -1, '');
/*																	--Index 2238*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', 														'', '', 	-1, -1, -1, '');
/*Ice Fan															--Index 2239*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Ice Fan', 										'Action', 'Offense', 	2, 1, -1, '0SW, SWEEP 2, ICE');
/*Frozen Stiff														--Index 2240*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Frozen Stiff', 									'Action', 'Offense', 	2, 3, -1, '0MA, LANCE 4, ICE');
/*Ice King															--Index 2241*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Ice King', 										'Action', 'Support', 	2, -1, 3, '3RG, BURST 1, IMMOBILE');

