--SDE
--1.0 Custom
--Abilities


/*Double Strike 							--Index 2301*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Double Strike', 			'Action', 'Offense', 1, 	0, 		0,	'MASSIVE DAMAGE, FRAGILE');
/*Axe Wind 									--Index 2302*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Axe Wind', 				'Action', 'Offense', 2, 	0,		-1,	'WAVE 2, MASSIVE DAMAGE, KNOCKDOWN, DANGEROUS');
/*Wrath of the Amazon 						--Index 2303*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Wrath of the Amazon', 	'Action', 'Offense', 3, 	0, 		0,	'RAGE, MASSIVE DAMAGE');
/*Spirit of the Jungle						--Index 2304*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Spirit of the Jungle', 	'Action', 'Offense', 3, 	0, 		2,	'2RG, BACKLASH, RESURRECTION or remove all wounds.');
/*Tiger's Grace								--Index 2305*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Tiger''s Grace', 			'Potion', 'Support', 1, 	-1,		0,	'+3MO');
/*Summon Tiger								--Index 2306*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Summon Tiger', 			'Potion', 'Support', 2, 	-1, 	1,	'Summon Tiger');

/*Poison Dart								--Index 2307*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Poison Dart', 			'Action', 'Offense', 1, 	0, 		6,	'Summon Tiger');
/*Killing Blow								--Index 2308*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Killing Blow', 			'Action', 'Offense', 2, 	0, 		2,	'Summon Tiger');
/*From the Skies							--Index 2309*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'From the Skies', 			'Action', 'Offense', 3, 	0, 		4,	'Summon Tiger');
/*Marked for Death							--Index 2310*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Marked for Death', 		'Action', 'Offense', 3, 	0, 		-1,	'Marked for Death');
/*There, Not There							--Index 2311*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'There, Not There', 		'Potion', 'Support', 1, 	-1, 	0,	'WAVE 1 SMOKE, then TELEPORT to any space on current tile.');

/*Smash										--Index 2312*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Smash', 					'Action', 'Offense', 1, 	0, 		-1,	'SPRAY 2, KNOCKDOWN, STUN, DANGEROUS');
/*Clear a Path								--Index 2313*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Clear a Path', 			'Action', 'Offense', 2, 	0, 		-1,	'SWEEP 2, KNOCKDOWN, STUN, DANGEROUS');
/*Hammer Throw								--Index 2314*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Hammer Throw', 			'Action', 'Offense', 3, 	0, 		-1,	'5RG, BURST 1, KNOCKDOWN, STUN, DANGEROUS');
/*Rage of Thumpos							--Index 2315*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Rage of Thumpos', 		'Action', 'Offense', 3, 	0, 		-1,	'+1G ATT, KNOCKDOWN, PACIFY, DANGEROUS');
/*Roar										--Index 2316*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Roar', 					'Potion', 'Support', 1, 	-1, 	0,	'WAVE 2, WEAK.');
/*Roar										--Index 2317*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Roar', 					'Action', 'Offense', 1, 	0, 		-1,	'WAVE 2, WEAK, Stun, Cold.');
/*Panther's Fury							--Index 2318*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Panther''s Fury', 		'Action', 'Offense', 2, 	0, 		-1,	'SWEEP 3, KNOCKDOWN.');

/*Hold the Line								--Index 2319*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Hold the Line', 			'Action', 'Support', 1, 	-1, 	-1,	'AUGMENT, AURA 1, BACKLASH.');
/*Fury of the Foarming Mug					--Index 2320*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Fury of the Foarming Mug','Action', 'Offense', 2, 	0, 		-1,	'WAVE 2, FRAGILE, COLD.');
/*Dwarven Rage								--Index 2321*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Dwarven Rage', 			'Action', 'Offense', 3, 	0, 		-1,	'WAVE 3, PUSH 3, KNOCKDOWN.');
/*Ripple the Stone							--Index 2322*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Ripple the Stone', 		'Action', 'Offense', 3, 	0, 		-1,	'+1G ATT, SPRAY 5, KNOCKDOWN, STUN, DANGEROUS');
/*Age of Stone								--Index 2323*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Age of Stone', 			'Potion', 'Support', 1, 	-1, 	0,	'+1R ARM');

/*Hoof Smash								--Index 2324*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Hoof Smash', 				'Action', 'Offense', 1, 	0, 		1,	'AUGMENT, AURA 1, BACKLASH.');
/*Arrow of the Wind							--Index 2325*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Arrow of the Wind',		'Action', 'Offense', 2, 	4, 		8,	'8MI, HOOKSHOT, BURST 1.');
/*Rain of Arrows							--Index 2326*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Rain of Arrows', 			'Action', 'Offense', 3, 	4, 		8,	'8MI, BURST 3, PACIFY, DANGEROUS.');
/*Roots of Earth							--Index 2327*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Roots of Earth', 			'Action', 'Offense', 3, 	0, 		-1,	'+1G ATT, WAVE 3, IMMOBILE, CHOKE, PACIFY');
/*Energy of the Forest						--Index 2328*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Energy of the Forest', 	'Potion', 'Support', 1, 	-1, 	0,	'AUGMENT, +1AC.');

/*lay Hands									--Index 2329*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Lay Hands', 				'Action', 'Support', 1, 	-1, 	-1,	'AUGMENT, WAVE 2, HEAL 2, REMEDY.');
/*Godly Wrath								--Index 2330*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Godly Wrath',				'Action', 'Offense', 2, 	3, 		8,	'8MI, BURST 2, FIRE, MASSIVE DAMAGE, DANGEROUS.');
/*Resurrect									--Index 2331*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Resurrect', 				'Action', 'Support', 3, 	-1, 	8,	'RESURRECT.');
/*Mass Heal									--Index 2332*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Mass Heal', 				'Action', 'Support', 3, 	0, 		-1,	'AUGMENT, same tile: Full HEAL, REMEDY');
/*Blessing									--Index 2333*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Blessing', 				'Potion', 'Support', 1, 	-1, 	0,	'AUGMENT, +1R ATT, DEX, OR WILL.');
/*Righteous Path							--Index 2334*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Righteous Path', 			'Potion', 'Support', 2, 	-1, 	0,	'SWEEP 5, PUSH 2.');

/*Thrust									--Index 2335*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Thrust',	 				'Action', 'Offense', 1, 	-1, 	-1,	'2RG, MASSIVE DAMAGE.');
/*Charge									--Index 2336*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Charge',					'Action', 'Offense', 2, 	3, 		8,	'DANGEROUS, LANCE 3, KNOCKDOWN, STURDY.');
/*Cleave									--Index 2337*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Cleave', 					'Action', 'Offense', 3, 	-1, 	8,	'+1R ATT, LANCE 2, MASSIVE DAMAGE.');
/*Battle Directive							--Index 2338*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Battle Directive', 		'Action', 'Support', 3, 	-1, 	-1,	'AUGMENT, Chosen Hero gains 1 extra turn this round.');
/*Revive the Fallen							--Index 2339*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Revive the Fallen', 		'Potion', 'Support', 1, 	-1, 	-1,	'RESSURECT.');

/*Flaming Hands								--Index 2340*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Flaming Hands',	 		'Action', 'Offense', 1, 	0, 		-1,	'FLAMING HANDS.');
/*Fireball									--Index 2341*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Fireball',				'Action', 'Offense', 2, 	3, 		8,	'8MA, DANGEROUS, FIRE, STUN, KNOCKDOWN, BURST 2.');
/*Why Aren't You Running					--Index 2342*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Why Aren''t You Running', 'Action', 'Offense', 3, 	3, 		-1,	'WHY AREN''T YOU RUNNING.');
/*Meteor Shower								--Index 2343*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Meteor Shower', 			'Action', 'Support', 3, 	3, 		-1,	'METEOR SHOWER.');
/*Firebrand									--Index 2344*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Firebrand',		 		'Potion', 'Support', 2, 	-1, 	0,	'FIRE, +1B to ATT, DEX, or WILL.');
/*Flamewave									--Index 2345*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Flamewve', 				'Potion', 'Offense', 2, 	0, 		-1,	'DANGEROUS, SWEEP 5, FIRE, KNOCDOWN, STUN.');

/*Whirlwind									--Index 2346*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Whirlwind',	 			'Action', 'Offense', 1, 	0, 		-1,	'DANGEROUS, WAVE 1, KNOCKDOWN.');
/*Bullrush									--Index 2347*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Bullrush',				'Action', 'Offense', 2, 	0, 		-1,	'DANGEROUS, SWEEP 3, KNOCKDOWN.');
/*Axe Cleave								--Index 2348*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Axe Cleave', 				'Action', 'Offense', 3, 	0, 		-1,	'DANGEROUS, LANCE 6, KNOCKDOWN.');
/*Split the Soul							--Index 2349*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Split the Soul', 			'Action', 'Offense', 3, 	0, 		6,	'DANGEROUS, 6RG, +1G ATT, MASSIVE DAMAGE, HOOKSHOT, KNOCKDOWN.');
/*Field Dressing							--Index 2350*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Field Dressing',	 		'Potion', 'Support', 1, 	-1, 	0,	'REMEDY, HEAL 2.');

/*Demon Touch								--Index 2351*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Demon Touch',	 			'Action', 'Offense', 1, 	0, 		-1,	'1SW, CHOKE, SLOW.');
/*Wrath of the Demon						--Index 2352*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Wrath of the Demon',		'Action', 'Offense', 2, 	0, 		-1,	'DANGEROUS, 1SW, WAVE 2, IMMOBILE.');

/*Shield Smash								--Index 2353*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Shield Smash',			'Action', 'Offense', 1, 	0, 		-1,	'DANGEROUS, SWEEP 1, KNOCKDOWN.');
/*Shield and Sword							--Index 2354*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Shield and Sword', 		'Action', 'Offense', 2, 	0, 		-1,	'WAVE 1, BACKLASH.');
/*Precision Strike							--Index 2355*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Precision Strike', 		'Action', 'Offense', 3, 	0, 		-1,	'WAVE 2, +1B ATT, MASSIVE DAMAGE.');
/*Valor										--Index 2356*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Valor',			 		'Potion', 'Support', 1, 	-1, 	0,	'AUGMENT, AURA 2, +1B ATT.');

/*Magic Missiles							--Index 2357*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Magic Missiles',			'Action', 'Offense', 1, 	3, 		6,	'6MA, BURST 1, +1ST WILL.');
/*Pigbellies Smashing Fist					--Index 2358*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Pigbellies Smashing Fist','Action', 'Offense', 2, 	3, 		-1,	'0MA, DANGEROUS, SWEEP 4, KNOCKDOWN.');
/*Chain Lightning							--Index 2359*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Chain Lightning', 		'Action', 'Offense', 3, 	3, 		8,	'8MA, DANGEROUS, BURST 2, STUN.');
/*Acid Rain									--Index 2360*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Acid Rain', 				'Action', 'Offense', 3, 	3, 		8,	'8MA, DANGEROUS, BURST 3, CHOKE, FRAGILE, +1G WILL.');
/*Mental Fortitude							--Index 2361*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Mental Fortitude',		'Potion', 'Support', 1, 	-1, 	0,	'AUGMENT, +2B WILL.');
/*Choking Cloud								--Index 2362*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Choking Cloud',	 		'Potion', 'Support', 2, 	-1, 	3,	'3RG, DANGEROUS, BURST 2, CHOKE, POISON.');

/*Sweep the Floor							--Index 2363*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Sweep the Floor',			'Action', 'Offense', 1, 	0, 		-1,	'DANGEROUS, WAVE 1, KNOCKDOWN.');
/*Bolas										--Index 2364*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Bolas',					'Action', 'Offense', 2, 	0, 		5,	'5RG, BIND, IMMOBILE.');
/*Disable									--Index 2365*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Disable', 				'Action', 'Offense', 3, 	0, 		2,	'2RG, KNOCKDOWN, FRAGILE, SLOW.');
/*End It									--Index 2366*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'End It', 					'Action', 'Offense', 3, 	0, 		-1,	'DANGEROUS, WAVE 1, KNOCKDOWN, FRAGILE, +1G ATT.');
/*Dirty Fighting							--Index 2367*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Dirty Fighting',			'Potion', 'Support', 1, 	-1, 	-1,	'DANGEROUS, SPRAY 2, WEAK, STUN.');

/*Mageshield								--Index 2368*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Mageshield',					'Action', 'Support', 1, 	0, 		0,	'AUGMENT, +1B ARM, BACKLASH.');
/*Mungs Acid Arrow							--Index 2369*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Mungs Acid Arrow',			'Action', 'Offense', 2, 	3, 		-1,	'DANGEROUS, SPRAY 4, FRAGILE, KNOCKDOWN.');
/*Ah, FIREBALL								--Index 2370*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Ah, FIREBALL', 				'Action', 'Offense', 3, 	3, 		8,	'8MA, DANGEROUS, BURST 3, FIRE, STUN, CHOKE.');
/*Death										--Index 2371*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Death', 						'Action', 'Offense', 3, 	0, 		-1,	'DANDYLES DEATH.');
/*Will of the Gods							--Index 2372*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Will of the Gods',			'Potion', 'Support', 1, 	-1, 	0,	'AUGMENT, +1B WILL.');
/*Summon Greater Shadow						--Index 2373*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Summon Greater Shadow Demon',	'Potion', 'Support', 2, 	-1, 	1,	'GREATER SHADOW DEMON.');

/*Heal										--Index 2374*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Heal',						'Action', 'Support', 1, 	-1, 	1,	'AUGMENT, 1RG, HEAL 2.');
/*Clear the Floor							--Index 2375*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Clear the Floor',				'Action', 'Offense', 2, 	0, 		-1,	'WAVE 1, PUSH 2.');
/*Chi Fan									--Index 2376*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Chi Fan', 					'Action', 'Offense', 3, 	0, 		-1,	'SPRAY 4, KNOCKDOWN, SLOW.');
/*Chi Burst									--Index 2377*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Chi Burst', 					'Action', 'Offense', 3, 	0, 		-1,	'DANGEROUS, +1G ATT, WAVE 4, KNOCKDOWN, SLOW.');
/*Focus										--Index 2378*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Focus',						'Potion', 'Support', 1, 	-1, 	0,	'AUGMENT, +1B ATT, WILL, DEX, +1AC, or +2MO.');

/*Bite Lip									--Index 2379*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Bite Lip', 					'Action', 'Support', 1, 	-1, 	0,	'AUGMENT, +1ST.');
/*Crack Skulls								--Index 2380*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Crack Skulls', 				'Action', 'Offense', 2, 	0, 		-1,	'+1R ATT, SWEEP 1, KNOCKDOWN.');
/*Orqish Ale								--Index 2381*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Orqish Ale',					'Potion', 'Support', 1, 	-1, 	0,	'AUGMENT, HEAL 2, REMEDY.');

/*Net Trap									--Index 2382*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Net Trap',					'Action', 'Offense', 1, 	0, 		3,	'3RG, BURST 1, IMMOBILE.');
/*Poultice									--Index 2383*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Poultice',					'Action', 'Support', 2, 	-1, 	0,	'AUGMENT, AURA 1, HEAL 2.');
/*Popshot									--Index 2384*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Popshot', 					'Action', 'Offense', 3, 	4, 		6,	'BURST 1, +1R DEX, KNOCKDOWN.');
/*Make it Count								--Index 2385*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Make it Count', 				'Action', 'Offense', 3, 	4, 		8,	'8MI, +1G DEX, FRAGILE, KNOCKDOWN, MASSIVE DAMAGE.');
/*Focus										--Index 2386*/ 		insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('1.0 Custom', 'Default', 'Accuracy',					'Potion', 'Support', 1, 	-1, 	0,	'AUGMENT, +1B ATT, WILL, or DEX.');










