--Table Load 2
--1.0 Abilities
/*Acorn Grenade 		--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Acorn Grenade', 'Action', 'Offense', 2, 0, 6, 'Range 6, Burst 1, Knockdown, Dangerous', '1.0');
/*Alluring				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Alluring', 'Action', 'Offense', 2, 3, 4, '+1R WILL, If successful Vandella immediately heals one wound.', '1.0');
/*Arrow Storm			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Arrow Storm', 'Action', 'Offense', 2, 4, -1, 'DEX vs ARM, Spray 4', '1.0');
/*Ash Cloud				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Ash Cloud', 'Action', 'Support', 1, -1, -1, 'Aura 1, Choke', '1.0');
/*Astral Hammer 		--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Astral Hammer', 'Action', 'Offense', 2, 0, 2, 'Cross 2, Knockdown', '1.0');
/*Backblast				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Backblast', 'Action', 'Offense', 1, 0, -1, 'Wave 1, Push 2, Dangerous', '1.0');
/*Backstab 				--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Backstab', 'Action', 'Offense', 3, 0, 1, 'Massive Damage, +1G Attack', '1.0');
/*Bamf! 				--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Bamf!', 'Action', 'Support', 1, -1, -1, 'Wave 2, Smoke', '1.0');
/*Bear Charge 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Bear Charge', 'Action', 'Offense', 2, 0, 1, '+1R Attack, Knockdown', '1.0');
/*Bear Hug 				--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Bear Hug', 'Action', 'Offense', 2, 0, 1, 'Immobile, Weak', '1.0');
/*Black Cat				--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Black Cat', 'Action', 'Offense', 2, -1, -1, 'Wave 1, Fragile', '1.0');
/*Bomb's Away 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Bomb''s Away', 'Action', 'Offense', 2, 0, 6, 'Range 6, Burst 1, Knockdown, Dangerous', '1.0');
/*Boomerang 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Boomerang', 'Action', 'Support', 1, -1, 6, 'Range 6, Hookshot. Place target Treasure Chest in an empty square adjacent to Deeproot Scout', '1.0');
/*Bow 					--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Bow', 'Action', 'Offense', 1, 4, 8, 'Missile 8', '1.0');
/*Briar Armor			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Briar Armor', 'Action', 'Support', 1, -1, -1, 'Backlash', '1.0');
/*Broken Bones 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Broken Bones', 'Action', 'Offense', 1, 3, -1, '+1B WILL, Fragile', '1.0');
/*Burning Bile			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Burning Bile', 'Action', 'Offense', 2, 0, -1, 'Lance 6', '1.0');
/*Burning Blade 		--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Burning Blade', 'Action', 'Offense', 2, 0, -1, 'Sweep 1, +1R Attack, Fire', '1.0'); --Hero Wyrm Claw Exemplar
/*Burning Blade 		--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Burning Blade', 'Action', 'Offense', 2, 0, -1, 'Sweep 3, +1R Attack', '1.0'); --Mini-Boss Ser Snapjaw
/*Burning Bloom 		--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Burning Bloom', 'Potion', 'Support', 1, -1, -1, 'All non special attacks made by the affected Heor gain "Range 8, Fire".', '1.0');
/*Burning Chitin		--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Burning Chitin', 'Action', 'Support', 1, -1, -1, '+1R ARM, Backlash', '1.0'); --?Check values from Blaze Beetle card under Lava Whirl
/*Cat & Mouse			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Cat & Mouse', 'Action', 'Support', 1, 3, 6, 'Range 6, WILL vs WILL, Compel 3', '1.0');
/*Catnip 				--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Catnip', 'Potion', 'Support', 0, -1, -1, 'Place 1 Potion counter on any Hero''s card.', '1.0');
/*Catnip Bomb 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Catnip Bomb', 'Potion', 'Support', 1, 0, 6, 'Bac Range 6, Burst 2, Pacify', '1.0');
/*Cleave 				--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Cleave', 'Action', 'Offense', 1, -1, -1, 'Sweep 1, Dangerous', '1.0');
/*Come Hither			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Come Hither', 'Action', 'Support', 2,-1, -1, 'Wave 3, Compel 3', '1.0');
/*Confuse				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Confuse', 'Action', 'Support', 2, -1, -1, 'Wave 2, Compel 1, Dangerous', '1.0');
/*Corrosive Striked		--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Corrosive Striked', 'Action', 'Offense', 2, 4, 8, 'Missle 6, Fire.', '1.0');
/*Coup de Grace			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Coup de Grace', 'Action', 'Offense', 3, 0, 1, 'When Coup de Grace inflicts a wound it instead inflicts one wound for every star rolled by the attacker.  After the attack is resolved remove Dragon Lance from play regardless if damage was inflicted.', '1.0');
/*Crack the Whip 		--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Crack the Whip', 'Action', 'Support', 1, -1, -1, 'Compel 2', '1.0');
/*Crippling Smash		--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Crippling Smash', 'Action', 'Offense', 1, 0, 1, '+1G Attack, Massive Damage', '1.0');
/*Cursed Blade 				--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Cursed Blade', 'Action', 'Offense', 2, -1, -1, '+1R Attack, Fragile', '1.0'); --?Check values from Dread Knight card under Shallow Grave
/*Dark Aura				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Dark Aura', 'Action', 'Support', 1, -1, -1, '+1 Star Attack, Massive Damage', '1.0');
/*Daystar 				--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Daystar', 'Action', 'Offense', 2, 0, -1, 'Lance 8, Push 2', '1.0');
/*Deep One Attack		--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Deep One Attack', 'Action', 'Offense', 2, 3, -1, 'Magic, Cross 5, +1R WILL', '1.0');
/*Dimensional Draught 	--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Dimensional Draught', 'Potion', 'Support', 1, -1, -1, 'Hero affected by Dimensional Draught may immediately Teleport.', '1.0');
/*Dive Bomb				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Dive Bomb', 'Action', 'Offense', 2, 0, -1, 'Pacify', '1.0'); --? Check values from Wyrmling card under Egg Clutch
/*Dragon Breath			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Dragon Breath', 'Action', 'Offense', 2, 0, -1, 'Spray 5, Fire', '1.0');
/*Dragon Rage			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Dragon Rage', 'Action', 'Support', 1, -1, -1, 'Augment, Aura 3, All Kobolds gain +1B Attack', '1.0'); --? Check values from Dragon Priest card under Kobold Warrens
/*Dwarven Curse 		--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Dwarven Curse', 'Action', 'Support', 2, 0, -1, 'Wave 3, Pull 3, Attack vs WILL', '1.0');
/*Elixir 				--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Elixir', 'Potion', 'Support', 1, -1, -1, 'Heal 3, Remedy', '1.0');
/*Elixir of Light 		--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Elixir of Light', 'Potion', 'Support', 1, -1, -1, 'All melee attacks made by the affected Hero gain "Cross 1, Holy, Fire".', '1.0');
/*Energy Blast 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Energy Blast', 'Action', 'Offense', 2, 4, 8, 'Missile 8, Burst 1', '1.0');
/*Enervating Bite		--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Enervating Bite', 'Action', 'Offense', 2, 0, -1, '+1R Attack, Poison', '1.0'); --?Check values from Crypt Spider under Pumpkin Patch
/*Feast					--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Feast', 'Action', 'Offense', 2, 0, 1, '+1R Attack.  If Rock Gut inflicts a wound this attack he may immediately remove a wound counter.', '1.0');
/*Fire Storm			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Fire Storm', 'Action', 'Support', 1, 0, -1, 'Wave 2, Fire, Dangerous', '1.0');
/*Fire Water 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Fire Water', 'Potion', 'Support', 1, -1, -1, '+1B Attack, Fire', '1.0');
/*Fire Wave 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Fire Wave', 'Action', 'Offense', 2, -1, -1, 'Wave 1', '1.0');
/*Flicker				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Flicker', 'Action', 'Support', 1, -1, 0, 'Teleport (A model with Teleport may move to any empty square within ten squares and line of sight of their current square.)', '1.0');
/*Flintlock				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Flintlock', 'Action', 'Offense', 1, 4, 6, 'Missle 6, +1R DEX', '1.0');
/*Focused Shot 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Focused Shot', 'Action', 'Offense', 2, 0, 8, '+3R Attack', '1.0');
/*Fritz 				--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Fritz', 'Potion', 'Support', 1, -1, -1, '+1B Attack, Knockdown', '1.0');
/*Frozen Feet 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Frozen Feet', 'Action', 'Offense', 1, 3, -1, '+1B WILL, Cold', '1.0');
/*Furnace Vent			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Furnace Vent', 'Action', 'Offense', 3, -1, -1, 'Cross 3, Fire', '1.0'); --?Check values from Blaze Beetle card under Lava Whirl
/*Fury's Blood			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Fury''s Blood', 'Potion', 'Support', 0, -1, -1, '+1B ARM, Backlash', '1.0');
/*Ghastly Vigor			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Ghastly Vigor', 'Action', 'Support', 1, -1, -1, 'Augment, Aura 3, All Undead gain +1B Attack', '1.0');
/*Ghost Form			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Ghost Form', 'Action', 'Support', 1, -1, 0, 'Teleport', '1.0');
/*Halo Extract 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Halo Extract', 'Potion', 'Support', 1, -1, -1, 'Aura 1, +1ST ARM', '1.0');
/*Hammer of Judgement 	--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Hammer of Judgement', 'Action', 'Offense', 1, 0, -1, 'Cross 1, Push 1', '1.0');
/*Happily Ever After 	--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Happily Ever After', 'Potion', 'Support', 1, -1, -1, 'Discard a single drawn loot or relic card and immediately draw another.', '1.0');
/*Healer				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Healer', '', '', 0, 0, 0, 'When a model with Healer rolls a Heart on an attack roll they gain two Hearts instead of one if they successfully inflict a wound.', '1.0');
/*Heart Seeker			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Heart Seeker', 'Action', 'Offense', 2, 4, 8, 'Missle 8, +1R DEX, Hookshot', '1.0');
/*Herbalist 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Herbalist', 'Action', 'Support', 1, -1, -1, 'Augment, Range 6, Remedy', '1.0');
/*Hero's Balm 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Hero''s Balm', 'Potion', 'Support', 1, -1, -1, 'The current attack is applied to the Hero affected by Hero''s Balm as though they were the target of the attack instead.', '1.0');
/*Hightower 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Hightower', 'Action', 'Support', 2, -1, -1, 'Augment, Aura 3, +1ST ARM, Immune: Knockdown', '1.0');
/*Hobbled Hands 		--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Hobbled Hands', 'Action', 'Offense', 1, 3, -1, '+1B WILL< Weak', '1.0');
/*Holy Oil 				--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Holy Oil', 'Potion', 'Offense', 1, -1, 4, 'Rac Range 4, Burst 1, Holy, Fire', '1.0');
/*Holy Water 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Holy Water', 'Potion', 'Offense', 1, -1, 4, 'Bac Range 4, Burst 1, models hit suffer Vulnerable: Holy', '1.0');
/*Hot Pot				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Hot Pot', 'Action', 'Offense', 1, 0, -1, '+1B DEX, Fire', '1.0'); --Check values from Flinger card under Kobold Warrens
/*Iron Halo 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Iron Halo', 'Action', 'Support', 1, -1, -1, 'Augment, Aura 3, +1B ARM', '1.0');
/*Javelin				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Javelin', 'Action', 'Offense', 1, 4, 6, 'Missle 6, Fire.', '1.0');
/*Just a Drop			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Just a Drop', 'Action', 'Support', 1, -1, 0, 'Augment, Immune: Status Effects', '1.0');
/*Juxtapose				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Juxtapose', 'Action', 'Support', 1, -1, 4, 'WILL vs WILL.  Target model suffers Vulnerable: Magic.  Skullbat is destroyed (even if the action was unsuccessful).', '1.0'); --?Check values from Skullbat card from Pumpkin Patch
/*Lifesap				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Lifesap', 'Action', 'Offense', 1, -1, 1, 'Range 1.  Do not make an attack roll.  Target model takes one wound.  Death immediately heals one wound.', '1.0');
/*Magma					--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Magma', 'Action', 'Support', 1, -1, -1, 'Augment, Backlash', '1.0');
/*Magma Strike 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Magma Strike', 'Action', 'Offense', 2, 3, 8, '+3B WILL', '1.0');
/*Maiden's Favor 		--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Maiden''s Favor', 'Action', 'Support', 1, -1, 6, 'Augment, Range 6, +1B Attack', '1.0');
/*Maiden's Kiss 		--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Maiden''s Kiss', 'Action', 'Support', 1, -1, 2, 'Augment, Range 2, Heal 1', '1.0');
/*Maiden's Token 		--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Maiden''s Token', 'Action', 'Support', 1, -1, 6, 'Augment, Range 6, +1B WILL', '1.0');
/*Mend Bones 		--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Mend Bones', 'Action', 'Support', 1, -1, 6, 'Range 6, Raise', '1.0'); --?Check values from Dust Coven Necromancer, Dust Mage card from Shallow Grave
/*Molotov				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Molotov', 'Action', 'Offense', 2, 0, -1, '+1G ATT, Lance 6, One Use Only - Discard Fireflow Brew after using Molotov', '1.0');
/*Mr. Tomn 				--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Mr. Tomn', 'Potion', 'Support', 1, -1, -1, 'Augment, Aura 3, +1B ARM', '1.0');
/*Nourishing Berries	--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Nourishing Berries', 'Potion', 'Support', 1, -1, -1, 'All Heroes gain Healer', '1.0');
/*Pain					--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Pain', 'Action', 'Offense', 1, 4, 8, 'Missile 8, Poison', '1.0');
/*Pirate Snatch 		--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Pirate Snatch', 'Action', 'Offense', 2, 0, 1, '+1R Attack, If Pirate Snatch inflicts a wound advance the Loot-O-Meter one additional space', '1.0');
/*Pixie Dust 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Pixie Dust', 'Potion', 'Support', 1, -1, -1, '+1B DEX, Stealth', '1.0');
/*Portcullis Potion 	--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Portcullis Potion', 'Potion', 'Support', 1, -1, -1, 'Place a Hero Effect Token next to any doorway.  The next monster to move through that doorway suffers an attack equal to the Exemplar''s current attack.  Then remove the token.', '1.0');
/*POW! 					--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('POW!', 'Action', 'Offense', 2, 0, 2, '+1R Attack, Massive Damage', '1.0');
/*Purification 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Purification', 'Action', 'Support', 1, -1, 2, 'Augment, Range 2, Heal 1', '1.0'); --Hero Princess Malya
/*Purification 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Purification', 'Action', 'Support', 1, -1, -1, 'Augment, Cross 2, Heal 1, Remedy', '1.0'); --Hero Sister of Light
/*Purr 					--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Purr', 'Action', 'Support', 1, -1, -1, 'Wave 1, Compel 2', '1.0');
/*Rage 					--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Rage', 'Action', 'Offense', 3, -1, -1, 'After every square you move this turn immediately make one melee attack.  You may not make a Berserk attack on a turn you Rage.  Barbarian''s ARM is reduced to 2B until her next activation.', '1.0');
/*Rally Cry				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Rally Cry', 'Action', 'Support', 2, -1, -1, 'Augment, Wave 5, Pull 4', '1.0');
/*Renewed Vigor					--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Renewed Vigor', 'Action', 'Support', 2, -1, -1, 'Augment, Wave 2, Compel 3', '1.0'); --?Check values from Dust Coven Necromancer card from Shallow Grave
/*Rex Cuddle			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Rex Cuddle', 'Action', 'Offense', 2, 0, 2, 'Immobile, Weak', '1.0');
/*Rex Smash				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Rex Smash', 'Action', 'Offense', 3, 0, 2, '+1G Attack, Massive Damage', '1.0');
/*Riddle of Steel		--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Riddle of Steel', 'Action', 'Offense', 2, 0, 6, 'Range 6, Weak', '1.0');
/*Rook 					--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Rook', 'Potion', 'Support', 1, -1, -1, 'Hero drinking Rook potion may immediately Teleport.', '1.0');
/*Scratch 				--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Scratch', 'Potion', 'Offense', 1, -1, -1, 'Bac Wave 2, Slow', '1.0');
/*Second Chance			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Second Chance', 'Action', 'Support', 1, -1, -1, 'Resurrect one destroyed Hero.  One use only - Discard Withered Ring after using Second Change.', '1.0');
/*Serpent Coil			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Serpent Coil', 'Action', 'Offense', 2, 0, 1, 'Immobile, Weak', '1.0');
/*Shadow Breath			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Shadow Breath', 'Action', 'Support', 2, -1, -1, 'Augment, Aura 5, All Kobolds gain Stealth', '1.0'); --Check values from Dragon Priest card under Kobold Warrens
/*Shag Fest 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Shag Fest', 'Action', 'Offense', 1, 0, 1, 'Sweep 1, +1R Attack, Dangerous, Lycanthropy', '1.0');
/*Shapeshift			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Shapeshift', 'Action', 'Support', 1, -1, 0, 'Angry Bear', '1.0');
/*Shapeshift 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Shapeshift', 'Action', 'Support', 1, -1, 0, 'Deeproot Druid', '1.0');
/*Shapeshift			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Shapeshift', 'Action', 'Support', 1, -1, 0, 'Nocturne', '1.0');
/*Shapeshift			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Shapeshift', 'Action', 'Support', 1, -1, 0, 'Von Drakk', '1.0');
/*Shapeshift 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Shapeshift', 'Action', 'Support', 1, -1, 0, 'Von Wilder', '1.0');
/*Shapeshift 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Shapeshift', 'Action', 'Support', 1, -1, 0, 'Von Wilding', '1.0');
/*Shattered Sword 		--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Shattered Sword', 'Action', 'Offense', 3, 0, 1, '+1G Attack, Massive Damage', '1.0');
/*Shell Shock			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Shell Shock', 'Action', 'Support', 1, -1, 10, 'Augment, Range 10, Burst 2.  All Rocktops in the area of effect may immediately activate Turtle.', '1.0'); --?Check values from Bombardier card under Rock Pile
/*Shield Bash			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Shield Bash', 'Action', 'Offense', 2, 0, 1, '+1 Star Attack, Massive Damage', '1.0');
/*Shieldwall			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Shieldwall', 'Action', 'Support', 1, -1, 0, 'Augment, Aura 1, +1B ARM', '1.0'); --?Check values from Ironscale card under Kobold Warrens
/*Shocking Bolt			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Shocking Bolt', 'Action', 'Offense', 2, 0, 6, '+1R WILL, Knockdown, Stun', '1.0'); --?Check values from Curse Coven Witch under Pumpkin Patch
/*Silk Spinner			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Silk Spinner', 'Action', 'Support', 1, 0, -1, 'Spray 3, Slow, Dangerous', '1.0'); --?Check values from Crypt Spider under Pumpkin Patch
/*Skully 				--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Skully', 'Potion', 'Offense', 1, 0, -1, 'R Wave 2, +1R Attack, Dangerous', '1.0');
/*Smite 				--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Smite', 'Action', 'Offense', 2, 0, 1, '+1R Attack, Knockdown, Fire', '1.0');
/*Smoke Pot				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Smoke Pot', 'Action', 'Support', 1, 0, -1, 'Burst 1, Smoke', '1.0'); --?Check values from Flinger card under Kobold Warrens
/*Snare					--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Snare', 'Action', 'Support', 1, -1, -1, 'Pull 5', '1.0');
/*Sneak Attack!			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Sneak Attack!', 'Action', 'Offense', 2, 0, 5, '+1R Attack, Knockdown, Pounce (Before making an attack roll, immediately Fly up to 5 squares.  The model must end this movement adjacent to an enemy model.)', '1.0');
/*Solar Flare			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Solar Flare', 'Action', 'Offense', 2, 4, 8, 'Missile 8, Burst 1', '1.0');
/*Soothe				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Soothe', 'Action', 'Support', 1, -1, 6, 'Augment, Range 6, Heal 1 (A model affected by Heal may remove a number of wound counters or a number of status effect counters equal to the value of X.)', '1.0');
/*Soothing Soda			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Soothing Soda', 'Potion', 'Support', 1, -1, -1, 'Immune: Status Effects.', '1.0');
/*Sparkle Burst 		--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Sparkle Burst', 'Action', 'Offense', 2, -1, -1, 'Burst 1', '1.0');
/*Spearhead 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Spearhead', 'Action', 'Support', 1, 0, -1, 'Wave 3, Push 3, Attack vs WILL', '1.0');
/*Splash				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Splash', 'Action', 'Offense', 2, 3, 6, 'Magic 6, Burst 1, Fire', '1.0'); --Treasure Fire Gel Goo
/*Splash				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Splash', 'Action', 'Offense', 2, -1, 6, 'Range 6, Burst 1, +1R Attack', '1.0'); --Warband Burning Gel  --?Check values from Burning Gel card under Lava Whirl
/*Sprite Syrup 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Sprite Syrup', 'Potion', 'Support', 0, -1, -1, '+1ac', '1.0');
/*Star Shine 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Star Shine', 'Action', 'Support', 1, -1, -1, 'Augment, Immune: Status Effects', '1.0');
/*Sticky Tongue 		--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Sticky Tongue', 'Action', 'Offense', 1, 4, 2, 'Missile 2, vs DEX.  If successful, Miserable Toad gains either one heart or one potion, in addition to any that are rolled.', '1.0');
/*Stranglethorn			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Stranglethorn', 'Action', 'Offense', 2, -1, 6, 'Magic 6, Burst 1, Slow', '1.0');
/*Sugar Rush			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Sugar Rush', 'Potion', 'Support', 3, 1, -1, '+2ac', '1.0');
/*Swarm					--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Swarm', 'Action', 'Offense', 1, 0, -1, '+1R Attack if target is suffering Knockdown', '1.0'); --? Check values from Hatchlings card in Egg Clutch and Wyrmling card
/*Tail Sweep			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Tail Sweep', 'Action', 'Offense', 2, 0, -1, 'Sweep 2, Knockdown', '1.0');
/*Teeth & Fur 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Teeth & Fur', 'Action', 'Offense', 2, 0, 5, '+1R Attack, Knockdown, Pounce', '1.0');
/*Terrifying Screech	--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Terrifying Screech', 'Action', 'Offense', 2, 0, -1, 'Wave 3, Stun', '1.0');
/*Thick Shell			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Thick Shell', 'Action', 'Support', 1, -1, -1, 'Augment, Immune: Status Effects', '1.0'); --?Check values from Crusher card under Rock Pile
/*Thwack!			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Thwack!', 'Action', 'Support', 1, -1, -1, 'Push target Shell up to six squares.  If the Shell moves into a square adjacent to a Hero its movement immediately stops.  The Roller then makes an attack roll against the Hero with 1B for every square the Shell moved.  This roll does not use the Roller''s Attack attribute.', '1.0'); --?Check values from Roller card under Rock Pile
/*Thwomp				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Thwomp', 'Action', 'Offense', 1, 0, 2, 'Push 5', '1.0');
/*Tide of Bones			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Tide of Bones', 'Action', 'Support', 2, -1, -1, 'Wave 2, Raise', '1.0');
/*Transmogrify			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Transmogrify', 'Potion', 'Offense', 1, 0, 6, 'B Shapeshift target model in melee with Witch into Miserable Toad.  Remove Witch''s potion counter.', '1.0'); --?Check values from Curse Coven Witch under Pumpkin Patch
/*Tremor Strike			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Tremor Strike', 'Action', 'Offense', 2, 0, -1, 'Wave 1', '1.0');
/*Turtle Cannon			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Turtle Cannon', 'Action', 'Offense', 1, -1, 10, 'Range 10, Burst 2, +1B Attack', '1.0'); --?Check values from Bombardier card under Rock Pile
/*Turtle Power			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Turtle Power', 'Action', 'Support', 1, -1, -1, 'Immediately activate Turtle.', '1.0'); --?Check values from Bombardier card under Rock Pile
/*Turtle Tremor			--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Turtle Tremor', 'Action', 'Offense', 2, -1, -1, 'Wave 3, +1B Attack for every Shell in the area of effect.', '1.0'); --?Check values from Crusher card under Rock Pile
/*Vending Machine		--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Vending Machine', 'Action', 'Support', 1, -1, 6, 'Augment, Range 6. Remove a single potion counter from Candy''s card and place it on target Hero''s card.', '1.0');
/*Volcano				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Volcano', 'Action', 'Offense', 2, 0, -1, 'Wave 3', '1.0'); 
/*Whip Master 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Whip Master', 'Action', 'Offense', 2, 0, 2, '+1 Attack, Pacify', '1.0');
/*White Mage Potion 	--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('White Mage Potion', 'Potion', 'Support', 1, -1, -1, 'Augment, Wave 5, Heal 1', '1.0');
/*Wibble				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Wibble', 'Action', 'Offense', 1, 4, 8, 'Missle 8, Stun', '1.0');
/*Wink					--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Wink', 'Action', 'Offense', 2, 3, 4, 'Magic 4, Weak, Pacify', '1.0');
/*Wizard Wings 			--Index 0*/ 	insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Wizard Wings', 'Potion', 'Support', 1, -1, -1, '+1B WILL, Fly', '1.0');
/*X Marks the Spot		--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('X Marks the Spot', 'Action', 'Support', 2, -1, 0, 'Draw and equip 1 Loot card', '1.0');
/*Zealotry				--Index 0*/		insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription, AbilityVersion) VALUES ('Zealotry', 'Action', 'Support', 1, -1, -1, 'Augment, Aura 2, +1B Attack', '1.0');

--2.0 or FK
insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription) VALUES ('Silver Star', 'Action', 'Offense', 2, 1, -1, 'Cross 3');
insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription) VALUES ('Silver Lance', 'Action', 'Offense', 2, 1, 1, '+1R Strength, Pounce');
insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription) VALUES ('Quicksilver Elixir', 'Potion', 'Emergency', 1, -1, -1, 'Augment, Reroll any number of dice from the last defense roll made.');
insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription) VALUES ('Happy Cat', 'Action', 'Support', 1, -1, -1, 'Wave 3, Pull 2.');
insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription) VALUES ('Rampant Growth', 'Action', 'Support', 1, -1, -1, 'Augment, Aura 3, all Kodama and Kinoko gain +1B Strength.');
insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription) VALUES ('Wine Tasting', 'Action', 'Support', 2, '', 'Augment, Wave 3, Heal 2.');
insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription) VALUES ('Seek The Leader', 'Action', 'Offense', 1, 'Dexterity', 6, '+1R dexterity, Massive Damage.  Discard this treasure after taking this action.');
insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription) VALUES ('Rampant Growth', 'Action', 'Support', 0, '', 'Augment, Lil'' Sprouts gain +1ST strength.');
insert into Abilities (Name, AbilityResource, AbilityType, AbilityCost, AbilityAttribute, AbilityRange, AbilityDescription) VALUES ('Sticky', 'Action', 'Support', 0, -1, -1, 'Models may not move for the remainder of this activation or their next activation, then remove the template from play.');

