' ' > TableLoad_Main.sql
' ' > TableLoad_A_1.0.1.sql
' ' > TableLoad_B_FK.sql
' ' > TableLoad_C_2.0.1.sql
' ' > TableLoad_D_1.0.2.sql
' ' > TableLoad_E_1.0_Custom.sql
' ' > TableLoad_F_Custom.sql
' ' > TableLoad_G_2.0.2.sql
type .\Backup_1.0.1\TableLoad_01_Keywords.sql >> TableLoad_A_1.0.1.sql
type .\Backup_1.0.1\TableLoad_02_Abilities.sql >> TableLoad_A_1.0.1.sql
type .\Backup_1.0.1\TableLoad_10_Heroes.sql >> TableLoad_A_1.0.1.sql
type .\Backup_1.0.1\TableLoad_11_Booty.sql >> TableLoad_A_1.0.1.sql
type .\Backup_1.0.1\TableLoad_14_MiniBosses.sql >> TableLoad_A_1.0.1.sql
type .\Backup_1.0.1\TableLoad_15_Bosses.sql >> TableLoad_A_1.0.1.sql
type .\Backup_1.0.1\TableLoad_16_Warbands.sql >> TableLoad_A_1.0.1.sql
type .\Backup_1.0.1\TableLoad_20_Boss_Spawns.sql >> TableLoad_A_1.0.1.sql
type .\Backup_1.0.1\TableLoad_21_Equipment.sql >> TableLoad_A_1.0.1.sql
type .\Backup_1.0.1\TableLoad_40_Terrain.sql >> TableLoad_A_1.0.1.sql
type .\Backup_1.0.1\TableLoad_41_Utilities.sql >> TableLoad_A_1.0.1.sql

type .\Backup_FK\TableLoad_01_Keywords.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_02_Abilities.sql >> TableLoad_B_FK.sql
type .\Backup_2.0.1\TableLoad_01_Keywords.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_02_Abilities.sql >> TableLoad_C_2.0.1.sql
type .\Backup_1.0.2\TableLoad_01_Keywords.sql >> TableLoad_D_1.0.2.sql
type .\Backup_1.0.2\TableLoad_02_Abilities.sql >> TableLoad_D_1.0.2.sql
type .\Backup_1.0_Custom\TableLoad_01_Keywords.sql >> TableLoad_E_1.0_Custom.sql
type .\Backup_1.0_Custom\TableLoad_02_Abilities.sql >> TableLoad_E_1.0_Custom.sql
type .\Backup_Custom\TableLoad_01_Keywords.sql >> TableLoad_F_Custom.sql
type .\Backup_Custom\TableLoad_02_Abilities.sql >> TableLoad_F_Custom.sql
type .\Backup_2.0.2\TableLoad_01_Keywords.sql >> TableLoad_G_2.0.2.sql
type .\Backup_2.0.2\TableLoad_02_Abilities.sql >> TableLoad_G_2.0.2.sql
type _Tables.sql >> TableLoad_Main.sql
type TableLoad_A_1.0.1.sql >> TableLoad_Main.sql
type TableLoad_B_FK.sql >> TableLoad_Main.sql
type TableLoad_C_2.0.1.sql >> TableLoad_Main.sql
type TableLoad_D_1.0.2.sql >> TableLoad_Main.sql
type TableLoad_E_1.0_Custom.sql >> TableLoad_Main.sql
type TableLoad_F_Custom.sql >> TableLoad_Main.sql
type TableLoad_G_2.0.2.sql >> TableLoad_Main.sql
