' ' > TableLoad_Main.sql
' ' > TableLoad_A_1.0.sql
' ' > TableLoad_B_FK.sql
' ' > TableLoad_C_2.0.1.sql
' ' > TableLoad_D_1.0_Custom.sql
' ' > TableLoad_E_Custom.sql
' ' > TableLoad_F_2.0.2.sql
type .\Backup_1.0\TableLoad_01_Keywords.sql >> TableLoad_A_1.0.sql
type .\Backup_1.0\TableLoad_02_Abilities.sql >> TableLoad_A_1.0.sql
type .\Backup_1.0\TableLoad_10_Heroes.sql >> TableLoad_A_1.0.sql
type .\Backup_1.0\TableLoad_11_Booty.sql >> TableLoad_A_1.0.sql
type .\Backup_1.0\TableLoad_14_MiniBosses.sql >> TableLoad_A_1.0.sql
type .\Backup_1.0\TableLoad_15_Bosses.sql >> TableLoad_A_1.0.sql
type .\Backup_1.0\TableLoad_16_Warbands.sql >> TableLoad_A_1.0.sql
type .\Backup_1.0\TableLoad_20_Boss_Spawns.sql >> TableLoad_A_1.0.sql
type .\Backup_1.0\TableLoad_21_Equipment.sql >> TableLoad_A_1.0.sql
type .\Backup_1.0\TableLoad_40_Terrain.sql >> TableLoad_A_1.0.sql
type .\Backup_1.0\TableLoad_41_Utilities.sql >> TableLoad_A_1.0.sql
type .\Backup_FK\TableLoad_01_Keywords.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_02_Abilities.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_10_Heroes.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_11_Pets.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_12_Booty.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_13_Creeps.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_14_MiniBosses.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_15_Bosses.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_16_Warbands.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_20_Statlines.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_22_Arcade_Booty.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_23_Arcade_Creeps.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_24_Arcade_MiniBosses.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_25_Arcade_Bosses.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_26_Arcade_Warbands.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_30_Boss_Spawns.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_31_Equipment.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_40_Terrain.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_41_Utilities.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_42_Explores.sql >> TableLoad_B_FK.sql
type .\Backup_FK\TableLoad_50_Heroes.sql >> TableLoad_B_FK.sql
type .\Backup_2.0.1\TableLoad_01_Keywords.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_02_Abilities.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_10_Heroes.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_11_Pets.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_12_Booty.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_13_Creeps.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_14_Minibosses.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_15_Bosses.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_16_Warbands.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_22_Arcade_Booty.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_23_Arcade_Creeps.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_24_Arcade_MiniBosses.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_25_Arcade_Bosses.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_26_Arcade_Warbands.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_30_Boss_Spawns.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_31_Equipment.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_40_Terrain.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_41_Utilities.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_43_Plots.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_44_Challenges.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_45_MightyMonsterCards.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_46_Consul_Power_Ups.sql >> TableLoad_C_2.0.1.sql
type .\Backup_2.0.1\TableLoad_47_Difficulty.sql >> TableLoad_C_2.0.1.sql
type .\Backup_1.0_Custom\TableLoad_01_Keywords.sql >> TableLoad_D_1.0_Custom.sql
type .\Backup_1.0_Custom\TableLoad_02_Abilities.sql >> TableLoad_D_1.0_Custom.sql
type .\Backup_1.0_Custom\TableLoad_10_Heroes.sql >> TableLoad_D_1.0_Custom.sql
type .\Backup_1.0_Custom\TableLoad_11_Booty.sql >> TableLoad_D_1.0_Custom.sql
type .\Backup_1.0_Custom\TableLoad_14_MiniBosses.sql >> TableLoad_D_1.0_Custom.sql
type .\Backup_1.0_Custom\TableLoad_15_Bosses.sql >> TableLoad_D_1.0_Custom.sql
type .\Backup_1.0_Custom\TableLoad_16_Warbands.sql >> TableLoad_D_1.0_Custom.sql
type .\Backup_1.0_Custom\TableLoad_20_Boss_Spawns.sql >> TableLoad_D_1.0_Custom.sql
type .\Backup_1.0_Custom\TableLoad_21_Equipment.sql >> TableLoad_D_1.0_Custom.sql
type .\Backup_1.0_Custom\TableLoad_40_Terrain.sql >> TableLoad_D_1.0_Custom.sql
type .\Backup_1.0_Custom\TableLoad_41_Utilities.sql >> TableLoad_D_1.0_Custom.sql
type .\Backup_Custom\TableLoad_01_Keywords.sql >> TableLoad_E_Custom.sql
type .\Backup_Custom\TableLoad_02_Abilities.sql >> TableLoad_E_Custom.sql
type _Tables.sql >> TableLoad_Main.sql
type TableLoad_A_1.0.sql >> TableLoad_Main.sql
type TableLoad_B_FK.sql >> TableLoad_Main.sql
type TableLoad_C_2.0.1.sql >> TableLoad_Main.sql
type TableLoad_D_1.0_Custom.sql >> TableLoad_Main.sql
type TableLoad_E_Custom.sql >> TableLoad_Main.sql
type TableLoad_F_2.0.2.sql >> TableLoad_Main.sql
