--SDE
--2.0.4
--Abilities


/*Titanium Flakes											--Index 2242*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Titanium Flakes', 			'Potion', 'Emergency', 	1, -1, 0, 	'AUGMENT, Use this when this model is attacked and before dice are rolled; the attack automatically fails.');		
/*ARRRR!													--Index 2243*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'ARRRR!', 					'Action', 'Offense', 	1, 3, 1, 	'1MA, BANE');		
/*Mystery Meat												--Index 2244*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Mystery Meat', 			'Action', 'Support', 	1, -1, 1, 	'AUGMENT, 1RG, Discard a token from this Treasure card and roll 1G.  Heal 1 for each star rolled.  If HE-PO is rolled, the target suffers POISON.');		
/*Polly Got a Potion										--Index 2245*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Polly Got a Potion', 		'Action', 'Offense', 	1, 4, 1, 	'DEX vs DEX.  1RG.  Remove one potion token from target Hero and place it on this model''s card.');
/*Plugged Barrel											--Index 2246*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Plugged Barrel', 			'Action', 'Offense', 	0, 1, -1, 	'Wave 4, Massive Damage.  Destroy this model.');
/*Polly Wants a Potion										--Index 2247*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Polly Wants a Potion',		'Action', 'Offense', 	0, 1, 1, 	'If this attack succeeds, after resolving the current Challenge Card, draw a new Challenge Card and immediately resolve it.');
/*Boarding Action											--Index 2248*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Boarding Action', 			'Action', 'Support', 	1, -1, -1, 	'All other friendly Pirates on this tile may immediately perform the Fight command.');
/*Epic Duel													--Index 2249*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Epic Duel', 				'Action', 'Support', 	0, -1, 6, 	'Until the affected model inflicts a wound on Dread Scarlett, it may only target Dread Scarlett.');
/*Sanguine Blade											--Index 2250*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Sanguine Blade', 			'Action', 'Offense', 	0, 1, 6, 	'Massive Damage.  If Dread Scarlett is not in range, perform the Move command first.');
/*Run Red													--Index 2251*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Run Red', 					'Action', 'Support', 	0, -1, -1, 	'All other friendly Pirates immediately perform the Move command.');
/*Garlic Breath												--Index 2252*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Garlic Breath', 			'Action', 'Offense', 	0, 1, -1, 	'Wave 3, FIRE');
/*Ice Storm													--Index 2253*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Ice Storm', 				'Action', 'Offense', 	0, 1, -1, 	'Wave 3, ICE');
/*Fortification												--Index 2254*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 	'Fortitude', 				'Action', 'Support', 	0, -1, -1, 	'Aura 3, +1ST ARM');
/*Raging Oceans, The										--Index 2255*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 	'Raging Oceans, The', 		'Action', 'Offense', 	2, 1, -1, '4SW, +1R STR, Massive Damage');


/*Exploding Pumpkins										--Index 2256*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Exploding Pumpkins', 		'Action', 'Offense', 	2, 4, 5, 	'5MI, BURST 1');
/*Catvalry Charge											--Index 2257*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Catvalry Charge', 			'Action', 'Offense', 	1, 1, -1, 	'LANCE 3, CHARGE');
/*Find It!													--Index 2258*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Find It!', 				'Action', 'Support', 	1, -1, 5, 	'AUGMENT, 5RG, Target other Hero moves up to four squares towards any treasure chest.  This action may only be taken once per turn.');
/*Pumpkin Spice												--Index 2259*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Pumpkin Spice', 			'Potion', 'Support', 	1, -1, -1, 	'AUGMENT, Draw one Loot card and equip it or place it in the Backpack.');

/*Batting Eyelashes											--Index 2260*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Batting Eyelashes', 		'Action', 'Support', 	1, -1, 5, 	'AUGMENT, 6RG, Target other Hero moves up to five squares.  This action may only be taken once per turn.');
/*True Love													--Index 2261*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'True Love', 				'Potion', 'Support', 	1, -1, 6, 	'AUGMENT, 6RG, Target Enthralled Minion gains +2AC and +1R STR until the end of the turn.');
/*Enthralling Elixir										--Index 2262*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Enthralling Elixir', 		'Potion', 'Offense', 	1, 3, 5, 	'5MA, if this attack destroys an 8-BIT monster (Arcade: a minion), place its model adjacent to the Demon Matchmaker.  The monster is now an Enthralled Minion, use the appropriate Pet card.');

/*Return To Dust											--Index 2263*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Return To Dust', 			'Action', 'Offense', 	1, 3, 4, 	'4MA, BURST 1, MASSIVE DAMAGE.  In order to take this action, this Hero must discard one Lich artifact from an adjacent Hero (It is removed from the game).');
/*Dance of Bones											--Index 2264*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Dance of Bones', 			'Action', 'Support', 	1, -1, 6, 	'AUGMENT, 6RG, Target other Hero with any Lich Artifacts immediately takes a +2AC.  Then one Lich Artifact from the target may be moved to another Hoer within range.  This may only be used once per turn.');
/*A Little Taste of Death									--Index 2265*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Little Taste of Death, A', 'Potion', 'Support', 	1, -1, 0, 	'AUGMENT, This Hero flips over an unused Lich Artifact and gains any modifiers as if it had that artifact (then flip it back over and shuffle).');

/*Spider Swarm												--Index 2266*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Spider Swarm', 			'Action', 'Offense', 	2, 4, -1, 	'0MA, WAVE 1, POISON');
/*My Pretties!												--Index 2267*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'My Pretties!', 			'Action', 'Offense', 	2, 4, 2, 	'2MA, MASSIVE DAMAGE, IMPROVED CRITICAL, POISON');
/*Fetch!													--Index 2268*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Fetch!', 					'Action', 'Support', 	1, -1, 6, 	'6RG, Select a token on the dungeon map (including a treasure chest) and move it up to 2 squares.');
/*Antivenom													--Index 2269*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Antivenom', 				'Potion', 'Emergency', 	1, -1, 0, 	'Heal 1, IMMUNEALL');

/*For Mistress!												--Index 2270*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'For Mistress!', 			'Action', 'Offense', 	2, 1, 1, 	'1SW, +1R STR.  MASSIVE DAMAGE.  The Demon Matchmaker Heals 1 for each wound inflicted by this action.');

/*Drusilla Says												--Index 2271*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Drusilla Says', 			'Action', 'Offense', 	2, 3, 5, 	'5MA, If this attack inflicts a wound, the target performs one action, controlled by the Consul.');
/*Feeling Weak, love?										--Index 2272*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Feeling Weak, Love?', 		'Action', 'Offense', 	2, 3, 5, 	'5MA, MASSIVE DAMAGE, BANE');
/*Get Them!													--Index 2273*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Get Them!', 				'Potion', 'Support', 	1, -1, -1, 	'Up to 4 Skull Points worth of other monsters perform a basic offensive action.');

/*Exploding Pumpkins										--Index 2274*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Exploding Pumpkins', 		'Action', 'Offense', 	0, 1, 5, 	'BURST 1, FIRE');
/*Catvalry Charge											--Index 2275*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Catvalry Charge', 			'Action', 'Offense', 	0, 1, -1, 	'LANCE 3');
/*Pumpkin Spice												--Index 2276*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Pumpkin Spice', 			'Action', 'Support', 	0, 1, 5, 	'+1ST STR, BANE');

/*Drusilla Says												--Index 2277*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Drusilla Says', 			'Action', 'Offense', 	0, -1, 5, 	'If this attack inflicts a wound, the target must immediately make one basic attack action targeting the closest other Hero.');
/*Feeling Weak, Love?										--Index 2278*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Feeling Weak, Love?', 		'Action', 'Offense', 	0, 1, 5, 	'BANE');

/*Blistering Armor											--Index 2279*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Blistering Armor', 		'Action', 'Support', 	0, -1, -1, 	'Wave 3, Push 3, KNOCKDOWN');
/*Armor Piercing Shell										--Index 2280*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Armor Piercing Shell', 	'Action', 'Offense', 	0, 1, 10, 	'MASSIVE DAMAGE, +2ST STR');

/*Maiden's Champion											--Index 2281*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Maiden''s Champion', 		'Action', 'Support', 	1, -1, 10, 	'AUGMENT, 10RG.  Target Hero may make a Basic Attack action.  This action may not target the same Hero twice in one turn.');
/*They Did It!												--Index 2282*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'They Did It!', 			'Action', 'Support', 	1, -1, 3, 	'AUGMENT, 3RG.  Gather all the Wrath tokens used this game and place them on target Hero.');
/*Dress-Up Party											--Index 2283*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Dress-Up Party', 			'Action', 'Support', 	1, -1, -1, 	'Draw a treasure and immediately equip it to any Hero, mark the treasure with a crystal token.  Discard the treasure at the start of this model''s next activation.');

/*Maiden's Kiss												--Index 2284*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Maiden''s Kiss', 			'Potion', 'Emergency', 	1, -1, 0, 	'AUGMENT, Regenerate');

/*Rune 'em Down												--Index 2285*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Rune ''em Down', 			'Action', 'Support', 	0, -1, 0, 	'This model moves four squares towards the closest Hero.  It will move into the same square as the Hero if able.  Any Heroes whose square this model moves over during this move suffer one wound and Knockdown and must be placed into an adjacent square.');

/*Dark Gifts												--Index 2286*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Dark Gifts', 				'Action', 'Support', 	0, -1, 1, 	'Spawn a Dark Present adjacent to this model.');
/*Pig Feed													--Index 2287*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Pig Feed', 				'Action', 'Offense', 	0, -1, 3, 	'+2 STR, Massive Damage.');

/*Hooves of Fury											--Index 2288*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Hooves of Fury',			'Action', 'Offense', 	2, 1, -1, 	'0SW, LANCE 4, CHARGE');
/*Pig Feed													--Index 2289*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 	'Pig Feed', 				'Action', 'Offense', 	2, 1, 3, 	'3SW, +1R STR, IMPROVED CRITICAL, MASSIVE DAMAGE');
/*Dark Gifts												--Index 2290*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 	'Dark Gifts', 				'Action', 'Support', 	1, -1, 1, 	'6RG, Roll 1R and spawn a number of Dark Presents adjacent to target Hero equal to the number of stars rolled (up to a max of four Dark Presents in play).');
/*Surprise Present											--Index 2291*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Surprise Present', 		'Action', 'Support', 	1, -1, 6, 	'6RG, Helpful Gifts');

/*Gifts of Darkness											--Index 2292*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Gifts of Darkness',		'Action', 'Support', 	1, 3, 1, 	'1RG, WILL vs WILL, INVADER.  Draw 1 Loot and place it under this card.  All SUPER monsters in play gain the benefits of the Loot as if they had it equipped.  Discard the Loot once this monster is destroyed.  Heroes Invaded by this monster may not target the Dungeon Boss with attacks.');

/*Surprisingly Fierce										--Index 2293*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Surprisingly Fierce',		'Action', 'Support', 	1, -1, 6, 	'6RG, HEAL 2, REMEDY.  This action may only be used once per turn.');

/*Flaming Coals												--Index 2294*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Flaming Coals',			'Action', 'Offense', 	2, 4, 4, 	'4MI, BANE, FIRE');

/*Truffle Hunt												--Index 2295*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Truffle Hunt',				'Action', 'Support', 	1, -1, 6, 	'6RG, HEAL 2, REMEDY.  This action may only be used once per turn.');
/*Bacon Grease												--Index 2296*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Bacon Grease',				'Potion', 'Support', 	1, -1, 0, 	'AUGMENT, +1MO.');


