--SDE
--2.0.4
--Keywords


/*Here Polly					--Index 1156*/	insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('2.0', 'Default', 'Here Polly', 					'Spawn a Potion Parrot within 3 squares of the dungeon boss.  Then spawn Loose Cannons anywhere in the dungeon until there are four in play.');
/*Cannons On Dack!				--Index 1157*/	insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('2.0', 'Default', 'Cannons On Dack!', 			'Spawn Loose Cannons anywhere in the dungeon until there are four in play.');
/*Brew a Special Potion			--Index 1158*/	insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('2.0', 'Default', 'Brew a Special Potion', 		'During his activation, Black-Handed Henry may discard a potion token and place it on this card.  Have 4 potion tokens on this card during the Power-Up Phase to accomplish this quest.<br><br>When this quest is accomplished, equip the Invulnerabilty Potion equipment card on the reverse side of this card.  It may remain equipped for the entire campaign, unless you choose to discard it.');
/*Learn Lily's Secret			--Index 1159*/	insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('2.0', 'Default', 'Learn Lily''s Secret', 		'Be within three squares of the Lily token when Lily is rescued in Scenario 4: Rescue Lily or Scenario 5: Devil Child. When this quest is accomplished, equip the Devil Island Map equipment card on the reverse side of this card. It may remain equipped for the entire campaign, unless you choose to discard it.');
/*Retrieve The Lost Treasure	--Index 1160*/	insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('2.0', 'Default', 'Retrieve The Lost Treasure', 	'In any scenario, while Kiji is on a treasure pile square, trade four loot from the backpack in order to draw a treasure card.<br></br>When this quest is accomplished, equip the Lost Coin equipment card on the reverse side of this card. It may remain equipped for the entire campaign, unless you choose to discard it.');
/*Beat Up Some Ijin				--Index 1161*/	insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('2.0', 'Default', 'Beat Up Some Ijin', 			'In any scenario which has Ibaraki-doji, deal the last wound to Ibaraki-doji and destroy it.<br></br>When this quest is accomplished, equip the Lucky Peach equipment card on the reverse side of this card. It may remain equipped for the entire campaign, unless you choose to discard it.');
/*Eat All The Dumplings!		--Index 1162*/	insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('2.0', 'Default', 'Eat All The Dumplings!', 		'At the end of Scenario 3: Food Fight or Scenario 4: Rescue Lily, have at least two dumpling tokens on Adzuki''s card.<br></br>When this quest is accomplished, equip the Obaa-San Dumpling equipment card on the reverse side of this card. It may remain equipped for the entire campaign, unless you choose to discard it.');
/*Reckless						--Index 1163*/	insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('2.0', 'Explore', 'Reckless', 					'When a model with Reckless attacks, its target may score Criticals on their defending roll; if the enemy scores a Critical, this model suffers a wound.');
/*Reckless						--Index 1164*/	insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('2.0', 'Arcade', 'Reckless', 						'When this model rolls 0 stars during an attack, it suffers a wound.');
/*New Brew						--Index 1165*/	insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('2.0', 'Default', 'New Brew', 					'When a model with New Brew activates, roll 1R and apply one of the following effects depending on the roll:<br>0 Stars: +1MO<br>1 Star: +1R STR<br>2+ Stars: This model''s attacks gain BANE');
/*Here Polly					--Index 1166*/	insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('2.0', 'Default', 'Here Polly', 					'When a model with Here Polly spawns, spawn a Potion Parrot within 3 squares of it.');
/*Greed							--Index 1167*/	insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('2.0', 'Arcade', 	'Greed', 						'When a model with Greed makes an attack, it gains +1ST for each Princess Coin the Heroes have used this game.');
/*Shame!						--Index 1168*/ 	insert into Keywords (KeywordVersion, PlayMode, Name, KeywordDescription) VALUES ('2.0', 'Arcade', 'Shame!', 'After a model with Shame! is destroyed, the model that destroyed it suffers Push 6.');

