--SDE
--2.0.4
--Abilities


/*Titanium Flakes											--Index 2242*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Titanium Flakes', 			'Potion', 'Emergency', 	1, -1, 0, 	'AUGMENT, Use this when this model is attacked and before dice are rolled; the attack automatically fails.');		
/*ARRRR!													--Index 2243*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'ARRRR!', 					'Action', 'Offense', 	1, 3, 1, 	'1MA, BANE');		
/*Mystery Meat												--Index 2244*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Mystery Meat', 			'Action', 'Support', 	1, -1, 1, 	'AUGMENT, 1RG, Discard a token from this Treasure card and roll 1G.  Heal 1 for each star rolled.  If HE-PO is rolled, the target suffers POISON.');		
/*Polly Got a Potion										--Index 2245*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Polly Got a Potion', 		'Action', 'Offense', 	1, 4, 1, 	'DEX vs DEX.  1RG.  Remove one potion token from target Hero and place it on this model''s card.');
/*Plugged Barrel											--Index 2246*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Plugged Barrel', 			'Action', 'Offense', 	0, 1, -1, 	'Wave 4, Massive Damage.  Destroy this model.');
/*Polly Wants a Potion										--Index 2247*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Polly Wants a Potion',		'Action', 'Offense', 	0, 1, 1, 	'If this attack succeeds, after resolving the current Challenge Card, draw a new Challenge Card and immediately resolve it.');
/*Boarding Action											--Index 2248*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Boarding Action', 			'Action', 'Support', 	1, -1, -1, 	'All other friendly Pirates on this tile may immediately perform the Fight command.');
/*Epic Duel													--Index 2249*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Epic Duel', 				'Action', 'Support', 	0, -1, 6, 	'Until the affected model inflicts a wound on Dread Scarlett, it may only target Dread Scarlett.');
/*Sanguine Blade											--Index 2250*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Sanguine Blade', 			'Action', 'Offense', 	0, 1, 6, 	'Massive Damage.  If Dread Scarlett is not in range, perform the Move command first.');
/*Run Red													--Index 2251*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Run Red', 					'Action', 'Support', 	0, -1, -1, 	'All other friendly Pirates immediately perform the Move command.');
/*Garlic Breath												--Index 2252*/ insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Garlic Breath', 			'Action', 'Offense', 	0, 1, -1, 	'Wave 3, FIRE');
/*Ice Storm													--Index 2253*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Ice Storm', 				'Action', 'Offense', 	0, 1, -1, 	'Wave 3, ICE');
/*Fortification												--Index 2254*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 	'Fortitude', 				'Action', 'Support', 	0, -1, -1, 	'Aura 3, +1ST ARM');
/*Raging Oceans, The										--Index 2255*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 	'Raging Oceans, The', 		'Action', 'Offense', 	2, 1, -1, '4SW, +1R STR, Massive Damage');
