--SDE
--2.0.2
--Abilities


/*Bubbles!														--Index 2019*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Bubbles!', 									'Potion', 'Support', 	1, -1, 0, 'AUGMENT, Roll 5B.  Heal 1 for each heart rolled.');
/*Cantina Coffee												--Index 2020*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Cantina Coffee', 							'Potion', 'Emergency', 	1, 2, 0, 'AUGMENT, +1B ARM, Protector');
/*Crab Juice													--Index 2021*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Crab Juice', 								'Potion', 'Emergency', 	1, 2, 0, 'AUGMENT, +1G ARM');
/*																--Index 2022*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', 					'', '', 	-1, -1, -1, '');
/*Double Cross													--Index 2023*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 'Double Cross', 								'Action', 'Offense', 	1, -1, -1, '6RG.  Target enemy model and this model trade places in the dungeon.  Then this model may make one basic offensive action.  This action may only be taken once per turn.');
/*Double Cross													--Index 2024*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Double Cross', 							'Action', 'Support', 	0, -1, -1, 'This model and the Hero with the least wrath immediately trade places in the dungeon.');
/*																--Index 2025*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', 	'', 						'', '', 	-1, -1, -1, '');
/*																--Index 2026*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', 	'', 							'', '', 	-1, -1, -1, '');
/*																--Index 2027*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', 	'', 							'', '', 	-1, -1, -1, '');
/*Fancy Sword Work												--Index 2028*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Fancy Sword Work', 						'Action', 'Offense', 	2, 1, -1, '0SW, Wave 1');
/*																--Index 2029*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', 	'', 								'', '', 	-1, -1, -1, '');
/*Flash of Blades												--Index 2030*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 	'Flash of Blades', 							'Action', 'Offense', 	2, 1, -1, '0SW, Wave 2, +1B STR');
/*Go.  Go.  Grabby Claws										--Index 2031*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Go.  Go.  Grabby Claws', 					'Action', 'Offense', 	2, 1, 4, '4SW, +2 STR, Pull 3, This action may Pull spawning points.');
/*																--Index 2032*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', 	'', 							'', '', 	-1, -1, -1, '');
/*I Just Stuffed Some Cutlery In There...						--Index 2033*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'I Just Stuffed Some Cutlery In There...', 	'Action', 'Offense', 	2, 4, -1, 'DANGEROUS, 0MI, Wave 8');
/*I Know														--Index 2034*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'I Know', 									'Action', 'Offense', 	1, -1, 1, 'AUGMENT, Range 1, Remedy');
/*Lead With The Beard											--Index 2035*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Lead With The Beard', 						'Action', 'Offense', 	2, 1, -1, '0SW, Lance 5, Charge');
/*																--Index 2036*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', 						'', '', 	-1, -1, -1, '');
/*																--Index 2037*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', 							'', '', 	-1, -1, -1, '');
/*																--Index 2038*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', 									'', '', 	-1, -1, -1, '');
/*Master Push													--Index 2039*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Master Push', 								'Action', 'Offense', 	2, 3, 3, '3MA, Push 6, KNOCKDOWN.  Any model that ends this push adjacent to a Wall or Structure Terrain suffers and additional Wound.');
/*Mind Trick													--Index 2040*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Mind Trick', 								'Action', 'Support', 	1, 3, 3, '3RG, WILL vs WILL, Compel 6');
/*MORE POWDER!													--Index 2041*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'MORE POWDER!', 								'Action', 'Offense', 	2, 4, 10, '10MI, MASSIVE DAMAGE, IMPROVED CRITICAL, BRUTAL STRIKE.  If this attack misses, this model suffers one wound.');
/*																--Index 2042*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', 						'', '', 	-1, -1, -1, '');
/*Pinch And Tear												--Index 2043*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Pinch And Tear', 							'Action', 'Offense', 	2, 1, 2, '2STR, +1R STR, Massive Damage');
/*Power of Prayer, The											--Index 2044*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Power of Prayer, The', 						'Action', 'Support', 	1, -1, 6, 'AUGMENT, 6RG, The target Heals 1 for each Prayer Slip this model has equipped.  This action may only be taken once per turn.');
/*Purifying Water												--Index 2045*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Purifying Water', 							'Potion', 'Support', 	1, -1, 0, 'AUGMENT.  DISCIPLINE');
/*Rum															--Index 2046*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Rum', 										'Potion', 'Emergency', 	1, -1, 0, 'AUGMENT, roll 1G and Heal 1 for each star rolled.  If no stars are rolled, suffer BANE.');
/*Scoundrel Slushie												--Index 2047*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Scoundrel Slushie', 							'Potion', 'Support', 	1, -1, -1, 'AUGMENT, Luck, Immediately open an adjacent treasure chest.');
/*Shoot First													--Index 2048*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Shoot First', 								'Potion', 'Support', 	2, 4, 8, '8MI, +1R DEX, Brutal Strike, Massive Damage');
/*Seal The Hatches												--Index 2049*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Seal The Hatches', 							'Action', 'Support', 	2, -1, -1, 'AUGMENT, Wave 2, Remedy');
/*Skuttle														--Index 2050*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Skuttle', 									'Action', 'Support', 	1, -1, 0, 'AUGMENT, Move 3.');
/*Soulmark														--Index 2051*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Soulmark', 									'Action', 'Offense', 	2, 3, 6, '6MA, BANE');
/*Soul Tether													--Index 2052*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Soul Tether', 								'Action', 'Offense', 	2, 3, 6, '6MA.  If this destroys its target, this model may equip one Prayer Slip to a slot that does not already have one.');
/*																--Index 2053*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', 													'', '', 	-1, -1, -1, '');
/*																--Index 2054*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', '', '', -1, -1, -1, '');
/*Storm of Blades												--Index 2055*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Storm of Blades', 'Action', 'Support', 1, -1, -1, 'AUGMENT, Aura 3, All models in range gain +1R to offense rolls due to Discipline instead of +1B.');
/*																--Index 2056*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', '', '', -1, -1, -1, '');
/*Tear Your Arms Off											--Index 2057*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Tear Your Arms Off', 						'Action', 'Support', 	1, 1, 2, '2SW, +1R STR, Massive Damage');
/*																--Index 2058*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', '', '', -1, -1, -1, '');
/*This Way To Treasure!											--Index 2059*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'This Way To Treasures!', 					'Action', 'Support', 	1, -1, 12, '12RG, move target Treasure Chest up to 6 squares.');
/*																--Index 2060*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', '', '', -1, -1, -1, '');
/*																--Index 2061*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', '', '', -1, -1, -1, '');
/*																--Index 2062*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', '', '', -1, -1, -1, '');
/*Black Powder													--Index 2063*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Black Powder', 							'Potion', 'Emergency', 	1, -1, 0, 'AUGMENT, Volatile');
/*Blade Wall													--Index 2064*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 	'Blade Wall', 								'Action', 'Support', 	1, -1, -1, 'AUGMENT, Aura 3.  All models in range gain +1R to defense rolls due to Discipline instead of +1B.');
/*																--Index 2065*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', '', '', -1, -1, -1, '');
/*Boarding Action												--Index 2066*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 	'Boarding Action', 							'Action', 'Support', 	1, -1, -1, 'All other friendly Pirates on this tile may immediately make one basic offensive action.');
/*																--Index 2067*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', '', '', -1, -1, -1, '');
/*Bow Bomb														--Index 2068*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Bow Bomb', 								'Action', 'Offense', 	2, 4, 6, '6MI, Burst 1, +1B DEX');
/*Black Coffee													--Index 2069*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Black Coffee', 								'Potion', 'Support', 	1, -1, 0, 'AUGMENT, +1AC');
/*Garlic Breath													--Index 2070*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Garlic Breath', 								'Potion', 'Offense', 	1, 4, 3, 'DANGEROUS, 3MI, Burst 1, FIRE');
/*Minty Fortress												--Index 2071*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Minty Fortress', 							'Potion', 'Emergency', 	1, -1, 0, 'AUGMENT, +1R ARM');
/*Polly Wants a Potion											--Index 2072*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 'Polly Wants a Potion', 						'Action', 'Offense', 	1, 4, 1, '1MI.  If this attack succeeds, place a potion token on this model''s card.');
/*Master Got a Potion											--Index 2073*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Master Got a Potion', 						'Action', 'Support', 	1, -1, 1, 'AUGMENT, 1RG.  Remove a potion token from this model''s card and give it to friendly model.');
/*Plugged Barrel												--Index 2074*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 'Plugged Barrel', 							'Action', 'Offense', 	1, 4, -1, '0MI, Wave 2, +1R DEX, Massive Damage.  Destroy this model.');
/*Man The Cannons!  Extra Shot!									--Index 2075*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Man The Cannons!  Extra Shot!', 				'Action', 'Offense', 	1, 4, 6, '6MI, +1G DEX, Massive Damage.  This model must destroy an adjacent Loose Cannon to take this action.');
/*New Brew														--Index 2076*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'New Brew', 									'Action', 'Support', 	1, 4, 0, 'AUGMENT,  Discard a Potion Token to equip one Relic Item.');
/*Feathered Friend												--Index 2077*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Feathered Friend', 							'Action', 'Support', 	1, -1, 3, 'If Potion Parrot is not in play, spawn Potion Parrot within three squares of this model.');
/*Soul Jar														--Index 2078*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Soul Jar', 									'Potion', 'Support', 	1, -1, 0, 'AUGMENT, Heal 1 for each unused Princess Coin the Heroes have remaining.');
/*All Hands On Deck!											--Index 2079*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'All Hands On Deck!', 						'Action', 'Support', 	1, -1, 0, 'All The Walking Curse models may move up to 4 squares.');

