--SDE
--2.0.2
--Abilities


/*Bubbles!														--Index 2019*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Bubbles!', 									'Potion', 'Support', 	1, -1, 0, 'AUGMENT, Roll 5B.  Heal 1 for each heart rolled.');

--!!!Clean before
--!!!Problems after

/*Cantina Coffee												--Index 2110*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Cantina Coffee', 							'Potion', 'Emergency', 	1, 2, 0, 'AUGMENT, +1B ARM, Protector');
/*Crab Juice													--Index 2111*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Crab Juice', 								'Potion', 'Emergency', 	1, 2, 0, 'AUGMENT, +1G ARM');

/*Dance of the Dead, The										--Index 2112*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Dance of the Dead, The', 					'Action', 'Offense', 	2, 4, -1, '0MI, Wave 1, POISON');
/*Double Cross													--Index 2113*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 'Double Cross', 								'Action', 'Offense', 	1, -1, -1, '6RG.  Target enemy model and this model trade places in the dungeon.  Then this model may make one basic offensive action.  This action may only be taken once per turn.');
/*Double Cross													--Index 2114*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Double Cross', 							'Action', 'Support', 	0, -1, -1, 'This model and the Hero with the least wrath immediately trade places in the dungeon.');

/*Essence of Vampire											--Index 2115*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Essence of Vampire', 						'Potion', 'Offense', 	1, -1, 0, 'AUGMENT.  Whenever this model deals a wound, it Heals 1.');
/*																--Index 2116*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', 	'', 							'', '', 	-1, -1, -1, '');
/*																--Index 2117*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', 	'', 							'', '', 	-1, -1, -1, '');

/*Fancy Sword Work												--Index 2118*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Fancy Sword Work', 						'Action', 'Offense', 	2, 1, -1, '0SW, Wave 1');
/*???														--Index 2119*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Fireworks', 								'Action', 'Offense', 	2, 3, 8, '8MA, Burst 1, KNOCKDOWN');
/*Flash of Blades												--Index 2120*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 	'Flash of Blades', 							'Action', 'Offense', 	2, 1, -1, '0SW, Wave 2, +1B STR');

/*Go.  Go.  Grabby Claws										--Index 2121*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Go.  Go.  Grabby Claws', 					'Action', 'Offense', 	2, 1, 4, '4SW, +2 STR, Pull 3, This action may Pull spawning points.');
/*Glitter Bomb													--Index 2122*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Glitter Bomb', 							'Potion', 'Offense', 	1, 3, 4, 'DANGEROUS.  4MA, Burst 1');

/*I Just Stuffed Some Cutlery In There...						--Index 2123*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'I Just Stuffed Some Cutlery In There...', 	'Action', 'Offense', 	2, 4, -1, 'DANGEROUS, 0MI, Wave 8');
/*I Know														--Index 2124*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'I Know', 									'Action', 'Offense', 	1, -1, 1, 'AUGMENT, Range 1, Remedy');

/*Lead With The Beard											--Index 2125*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Lead With The Beard', 						'Action', 'Offense', 	2, 1, -1, '0SW, Lance 5, Charge');
/*Lights In Your Eyes											--Index 2126*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Lights In Your Eyes', 						'Action', 'Support', 	1, 3, 6, '1RG, +1G WILL, WILL Vs. DEX, HEX');
/*Look Into My Eyes												--Index 2127*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Look Into My Eyes', 							'Action', 'Support', 	1, 3, 6, 'DANGEROUS, 6RG, WILL Vs. WILL, Compel 6');

/*																--Index 2128*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', 									'', '', 	-1, -1, -1, '');
/*Master Push													--Index 2129*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Master Push', 								'Action', 'Offense', 	2, 3, 3, '3MA, Push 6, KNOCKDOWN.  Any model that ends this push adjacent to a Wall or Structure Terrain suffers and additional Wound.');
/*Mind Trick													--Index 2130*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Mind Trick', 								'Action', 'Support', 	1, 3, 3, '3RG, WILL vs WILL, Compel 6');
/*MORE POWDER!													--Index 2131*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'MORE POWDER!', 								'Action', 'Offense', 	2, 4, 10, '10MI, MASSIVE DAMAGE, IMPROVED CRITICAL, BRUTAL STRIKE.  If this attack misses, this model suffers one wound.');

/*Night's Mercy, The											--Index 2132*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Night''s Mercy, The', 						'Action', 'Offense', 	2, 1, 2, '2SW, +1G STR, Massive Damage');

/*Pinch And Tear												--Index 2133*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Pinch And Tear', 							'Action', 'Offense', 	2, 1, 2, '2STR, +1R STR, Massive Damage');
/*Power of Prayer, The											--Index 2134*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Power of Prayer, The', 						'Action', 'Support', 	1, -1, 6, 'AUGMENT, 6RG, The target Heals 1 for each Prayer Slip this model has equipped.  This action may only be taken once per turn.');
/*Purifying Water												--Index 2135*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Purifying Water', 							'Potion', 'Support', 	1, -1, 0, 'AUGMENT.  DISCIPLINE');

/*Rum															--Index 2136*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Rum', 										'Potion', 'Emergency', 	1, -1, 0, 'AUGMENT, roll 1G and Heal 1 for each star rolled.  If no stars are rolled, suffer BANE.');

/*Scoundrel Slushie												--Index 2137*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Scoundrel Slushie', 							'Potion', 'Support', 	1, -1, -1, 'AUGMENT, Luck, Immediately open an adjacent treasure chest.');
/*Shoot First													--Index 2138*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Shoot First', 								'Potion', 'Support', 	2, 4, 8, '8MI, +1R DEX, Brutal Strike, Massive Damage');
/*Seal The Hatches												--Index 2139*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Seal The Hatches', 							'Action', 'Support', 	2, -1, -1, 'AUGMENT, Wave 2, Remedy');
/*Skuttle														--Index 2140*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Skuttle', 									'Action', 'Support', 	1, -1, 0, 'AUGMENT, Move 3.');
/*Soulmark														--Index 2141*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Soulmark', 									'Action', 'Offense', 	2, 3, 6, '6MA, BANE');
/*Soul Tether													--Index 2142*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Soul Tether', 								'Action', 'Offense', 	2, 3, 6, '6MA.  If this destroys its target, this model may equip one Prayer Slip to a slot that does not already have one.');
/*																--Index 2143*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', '', 													'', '', 	-1, -1, -1, '');
/*Stink Beard Bark												--Index 2144*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Stink Beard Bark', 'Action', 'Offense', 1, 0, -1, '0SW, Sweep 1, POISON');
/*Storm of Blades												--Index 2145*/	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Storm of Blades', 'Action', 'Support', 1, -1, -1, 'AUGMENT, Aura 3, All models in range gain +1R to offense rolls due to Discipline instead of +1B.');

/*Taste of You, A												--Index 2146*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Taste of You, A', 							'Action', 'Support', 	2, 3, 1, '1MA, +1R WILL.  Place a crystal token on the target if this action succeeds.  The next time the target activates, discard the token and this model controls the target''s first action of the activation.');
/*Tear Your Arms Off											--Index 2147*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Tear Your Arms Off', 						'Action', 'Support', 	1, 1, 2, '2SW, +1R STR, Massive Damage');
/*Tears of the Moon												--Index 2148*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Tears of the Moon', 							'Potion', 'Emergency', 	1, -1, 0, 'AUGMENT, Defender');
/*This Way To Treasures!										--Index 2149*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'This Way To Treasures!', 					'Action', 'Support', 	1, -1, 12, '12RG, move target Treasure Chest up to 6 squares.');

/*Vent Steam													--Index 2150*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Vent Steam', 								'Action', 'Offense', 	2, 1, -1, 'DANGEROUS, 0SW, +1B STR, Wave 1');
/*Viper''s Strike												--Index 2151*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Viper''s Strike', 							'Action', 'Offense', 	1, 1, 2, '2SW, +1B STR, Pounce.  This action may only be taken once per activation.');

/*At Your Back													--Index 2152*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'At Your Back', 								'Action', 'Support', 	1, -1, 4, 'AUGMENT, 4RG.  Switch places with target Hero.');

/*Black Powder													--Index 2153*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Black Powder', 							'Potion', 'Emergency', 	1, -1, 0, 'AUGMENT, Volatile');
/*Blade Wall													--Index 2154*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 	'Blade Wall', 								'Action', 'Support', 	1, -1, -1, 'AUGMENT, Aura 3.  All models in range gain +1R to defense rolls due to Discipline instead of +1B.');
/*Blade Wall													--Index 2155*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Arcade', 	'Blade Wall', 								'Action', 'Support', 	0, -1, -1, 'AUGMENT, Aura 3.  +2ST ARM');
/*Boarding Action												--Index 2156*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Boarding Action', 							'Action', 'Support', 	1, -1, -1, 'All other friendly Pirates on this tile may immediately make one basic offensive action.');
/*																--Index 2157*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('', '', 	'', 							'', '', 	-1, -1, -1, '');
/*Bow Bomb														--Index 2158*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 	'Bow Bomb', 								'Action', 'Offense', 	2, 4, 6, '6MI, Burst 1, +1B DEX');

/*Black Coffee													--Index 2159*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Black Coffee', 								'Potion', 'Support', 	1, 4, 3, 'DANGEROUS, 3MI, Burst 1, FIRE');
/*Garlic Breath													--Index 2160*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Garlic Breath', 								'Potion', 'Offense', 	1, -1, 0, 'AUGMENT, +1AC');
/*Minty Fortress												--Index 2161*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Minty Fortress', 							'Potion', 'Emergency', 	1, 2, 0, 'AUGMENT, +1R ARM');

/*Polly Wants a Potion											--Index 2162*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 'Polly Wants a Potion', 						'Action', 'Offense', 	1, 4, 1, '1MI.  If this attack succeeds, place a potion token on this model''s card.');
/*Master Got a Potion											--Index 2163*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Master Got a Potion', 						'Action', 'Support', 	1, -1, 1, 'AUGMENT, 1RG.  Remove a potion token from this model''s card and give it to friendly model.');

/*Plugged Barrel												--Index 2164*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Explore', 'Plugged Barrel', 							'Action', 'Offense', 	1, 4, -1, '0MI, Wave 2, +1R DEX, Massive Damage.  Destroy this model.');

/*Man The Cannons!  Extra Shot!									--Index 2165*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Man The Cannons!  Extra Shot!', 				'Action', 'Offense', 	1, 4, 6, '6MI, +1G DEX, Massive Damage.  This model must destroy an adjacent Loose Cannon to take this action.');
/*New Brew														--Index 2166*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'New Brew', 									'Action', 'Support', 	1, 4, 0, 'AUGMENT,  Discard a Potion Token to equip one Relic Item.');
/*Feathered Friend												--Index 2167*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Feathered Friend', 							'Action', 'Support', 	1, -1, 3, 'If Potion Parrot is not in play, spawn Potion Parrot within three squares of this model.');
/*Soul Jar														--Index 2168*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Soul Jar', 									'Potion', 'Support', 	1, -1, 0, 'AUGMENT, Heal 1 for each unused Princess Coin the Heroes have remaining.');


--!!!Problems before
--!!!Clean after

/*All Hands On Deck!											--Index 2079*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'All Hands On Deck!', 						'Action', 'Support', 	1, -1, 0, 'All The Walking Curse models may move up to 4 squares.');





