---2.0.2 Abilities
--2.0.2
/*At Your Back													--Index kXXX*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'At Your Back', 								'Action', 'Support', 	1, -1, 4, 'AUGMENT, 4RG.  Switch places with target Hero.');
/*Black Powder													--Index kXXX*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Black Powder', 								'Potion', 'Emergency', 	1, -1, 0, 'AUGMENT, Volatile');
/*Dance of the Dead, The										--Index kXXX*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Dance of the Dead, The', 					'Action', 'Offense', 	2, 4, -1, '0MI, Wave 1, POISON');
/*Essence of Vampire											--Index kXXX*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Essence of Vampire', 						'Potion', 'Offense', 	1, -1, 0, 'AUGMENT.  Whenever this model deals a wound, it Heals 1.');
/*Fireworks														--Index kXXX*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Fireworks', 									'Action', 'Offense', 	2, 3, 8, '8MA, Burst 1, KNOCKDOWN');
/*Glitter Bomb													--Index kXXX*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Glitter Bomb', 								'Potion', 'Offense', 	1, 3, 4, 'DANGEROUS.  4MA, Burst 1');
/*I Just Stuffed Some Cutlery In There...						--Index kXXX*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'I Just Stuffed Some Cutlery In There...', 	'Action', 'Offense', 	2, 4, -1, 'DANGEROUS, 0MI, Wave 8');
/*Lights In Your Eyes											--Index kXXX*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Lights In Your Eyes', 						'Action', 'Support', 	1, 3, 6, '1RG, +1G WILL, WILL Vs. DEX, HEX');
/*Look Into My Eyes												--Index kXXX*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Look Into My Eyes', 							'Action', 'Support', 	1, 3, 6, 'DANGEROUS, 6RG, WILL Vs. WILL, Compel 6');
/*MORE POWDER!													--Index kXXX*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'MORE POWDER!', 								'Action', 'Offense', 	2, 4, 10, '10MI, MASSIVE DAMAGE, IMPROVED CRITICAL, BRUTAL STRIKE.  If this attack misses, this model suffers one wound.');
/*Night's Mercy, The											--Index kXXX*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Night''s Mercy, The', 						'Action', 'Offense', 	2, 1, 2, '2SW, +1G STR, Massive Damage');
/*Power of Prayer, The											--Index kXXX*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Power of Prayer, The', 						'Action', 'Support', 	1, -1, 6, 'AUGMENT, 6RG, The target Heals 1 for each Prayer Slip this model has equipped.  This action may only be taken once per turn.');
/*Purifying Water												--Index kXXX*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Purifying Water', 							'Potion', 'Support', 	1, -1, 0, 'AUGMENT.  DISCIPLINE');
/*Soulmark														--Index kXXX*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Soulmark', 									'Action', 'Offense', 	2, 3, 6, '6MA, BANE');
/*Soul Tether													--Index kXXX*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Soul Tether', 								'Action', 'Offense', 	2, 3, 6, '6MA.  If this destroys its target, this model may equip one Prayer Slip to a slot that does not already have one.');
/*SparkleBOOM													--Index kXXX*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'SparkleBOOM', 								'Action', 'Offense', 	2, 3, 8, '8MA, +1R WILL, MASSIVE DAMAGE, IMPROVED CRITICAL');
/*Taste of You, A												--Index kXXX*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Taste of You, A', 							'Action', 'Support', 	2, 3, 1, '1MA, +1R WILL.  Place a crystal token on the target if this action succeeds.  The next time the target activates, discard the token and this model controls the target''s first action of the activation.');
/*Tears of the Moon												--Index kXXX*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Tears of the Moon', 							'Potion', 'Emergency', 	1, -1, 0, 'AUGMENT, Defender');
/*Viper''s Strike												--Index kXXX*/ 	insert into Abilities (AbilityVersion, PlayMode, Name, AbilityResource, AbilityType, AbilityCost, AttributeIndex, AbilityRange, AbilityDescription) VALUES ('2.0', 'Default', 'Viper''s Strike', 							'Action', 'Offense', 	1, 1, 2, '2SW, +1B STR, Pounce.  This action may only be taken once per activation.');





